const translations = {
    'fa': {
        'header-title': 'ثبت سفارش شرکت الکامهر کیمیا',
        'header-subtitle': 'تولیدکننده آلومینیوم خالص و آلیاژی',
        'choose-language-text': 'زبان خود را انتخاب کنید',
        'order-info-heading': 'اطلاعات سفارش',
        'order-type-label': 'نوع سفارش',
        'option-internal': 'سفارش داخلی',
        'option-customer': 'سفارش مشتری',
        'company-person-name-label': 'نام شرکت / شخص',
        'company_person_name_placeholder': 'نام شرکت یا شخص را وارد کنید',
        'contact-number-label': 'شماره تماس',
        'contact_number_placeholder': 'شماره تماس را وارد کنید',
        'delivery-date-label': 'تاریخ ایده آل برای دریافت سفارش',
        'delivery_date_placeholder': 'تاریخ را انتخاب کنید',
        'description-label': 'توضیح',
        'description_placeholder': 'توضیحات سفارش',
        'note-label': 'آدرس یا ایمیل را جهت ارتباط درج نمایید',
        'note_placeholder': 'آدرس یا ایمیل را جهت ارتباط درج نمایید',
        'next-step-1': 'مرحله بعد',
        'product-type-heading': 'نوع محصول',
        'product-alloy-ingot': 'شمش آلیاژی',
        'product-granule': 'گرانول',
        'product-wire': 'مفتول',
        'product-aac-conductor': 'هادی AAC',
        'product-aaac-conductor': 'هادی AAAC',
        'product-abc-conductor': 'هادی ABC',
        'product-acsr-conductor': 'هادی ACSR',
        'product-rod': 'راد',
        'product-Aluminium-tray': 'ظروف آلومینیوم',
        'prev-step-2': 'مرحله قبل',
        'next-step-2': 'مرحله بعد',
        'nav-back': 'بازگشت',
        'summary-heading': 'خلاصه و تایید سفارش',
        'summary-title': 'خلاصه سفارش شما',
        'summary-order-info': 'اطلاعات سفارش',
        'summary-product-details': 'جزئیات محصول',
        'summary-order-type': 'نوع سفارش:',
        'summary-company-person': 'نام شرکت / شخص:',
        'summary-contact-number': 'شماره تماس:',
        'summary-delivery-date': 'تاریخ تحویل:',
        'summary-description': 'توضیحات:',
        'summary-note': 'یادداشت:',
        'summary-product-type': 'نوع محصول:',
        'summary-submit': 'ثبت نهایی سفارش',
        // Product Specific Details
        'alloy-ingot-heading': 'جزئیات شمش آلیاژی',
        'alloy-type-label': 'نوع آلیاژ',
        'select-option-default-alloy': 'انتخاب کنید',
        'option-pure': 'خالص',
        'option-alloyed': 'آلیاژی',
        'packaging-label-alloy': 'بسته بندی',
        'select-packaging-default-alloy': 'انتخاب کنید',
        'option-bulk-alloy': 'فله',
        'option-pallet-alloy': 'پالت 1000 کیلوگرمی',
        'weight-label-alloy': 'وزن درخواستی (کیلوگرم)',
        'weight_placeholder': 'وزن درخواستی',
        'standard-label': 'استاندارد',
        'standard_placeholder': 'استاندارد',
        'chemical-analysis-label': 'اهم آنالیز شیمیایی',
        'chemical_analysis_placeholder': 'اهم آنالیز شیمیایی',
        'note-label-alloy': 'یادداشت',
        'note_placeholder_alloy': 'یادداشت‌های اضافی',
        'submit-alloy': 'تایید و نمایش خلاصه',
        'granule-heading': 'جزئیات گرانول',
        'granule-alloy-type-label': 'نوع آلیاژ',
        'select-granule-alloy-default': 'انتخاب کنید',
        'option-granule-pure': 'خالص',
        'option-granule-alloyed': 'آلیاژی',
        'granule-packaging-label': 'بسته بندی',
        'select-granule-packaging-default': 'انتخاب کنید',
        'option-jumbo': 'جامبو',
        'option-bulk-granule': 'فله',
        'granule-weight-label': 'وزن درخواستی (کیلوگرم)',
        'granule_weight_placeholder': 'وزن درخواستی',
        'granule-note-label': 'یادداشت',
        'granule_note_placeholder': 'یادداشت‌های اضافی',
        'submit-granule': 'تایید و نمایش خلاصه',
        'wire-heading': 'جزئیات مفتول',
        'wire-alloy-type-label': 'نوع آلیاژ',
        'select-wire-alloy-default': 'انتخاب کنید',
        'option-wire-pure': 'خالص',
        'option-wire-alloyed': 'آلیاژی',
        'anneal-label': 'آنیل',
        'select-anneal-default': 'انتخاب کنید',
        'option-anneal-yes': 'بشود',
        'option-anneal-no': 'نشود',
        'aging-label': 'ایجینگ',
        'select-aging-default': 'انتخاب کنید',
        'option-aging-yes': 'بشود',
        'option-aging-no': 'نشود',
        'wire-packaging-label': 'بسته بندی',
        'select-wire-packaging-default': 'انتخاب کنید',
        'option-reel-630': 'قرقره 630',
        'option-plastic-reel': 'قرقره پلاستیکی',
        'option-wood-reel': 'قرقره چوبی',
        'option-coil': 'کویل',
        'wire-cross-section-label': 'قطر (میلی‌متر)',
        'wire_cross_section_placeholder': 'قطر (میلی‌متر)',
        'order-by-label-wire': 'سفارش بر اساس',
        'wire-order-by-weight-text': 'وزن (کیلوگرم)',
        'wire-order-by-tiraj-text': 'متراژ (متر)',
        'wire-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'wire_weight_placeholder': 'وزن درخواستی',
        'wire-calculated-tiraj-label': 'متراژ محاسبه‌شده (متر)',
        'wire-tiraj-input-label': 'متراژ درخواستی (متر)',
        'wire-calculated-weight-label': 'وزن محاسبه‌شده (کیلوگرم)',
        'note-label-wire': 'یادداشت',
        'note_placeholder_wire': 'یادداشت‌های اضافی',
        'submit-wire': 'تایید و نمایش خلاصه',
        'aac-heading': 'جزئیات هادی AAC',
        'aac-packaging-label': 'بسته بندی',
        'select-aac-packaging-default': 'انتخاب کنید',
        'option-aac-metal-reel': 'قرقره فلزی',
        'option-aac-wood-reel': 'روی قرقره چوبی',
        'aac-cross-section-label': 'سطح مقطع نامی (میلی‌متر مربع)',
        'select-aac-cross-section-default': 'انتخاب کنید',
        'order-by-label-aac': 'سفارش بر اساس',
        'aac-order-by-weight-text': 'وزن (کیلوگرم)',
        'aac-order-by-tiraj-text': 'متراژ (متر)',
        'aac-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'aac_weight_placeholder': 'وزن درخواستی',
        'aac-calculated-tiraj-label': 'متراژ محاسبه‌شده (متر)',
        'aac-tiraj-input-label': 'متراژ درخواستی (متر)',
        'aac-calculated-weight-label': 'وزن محاسبه‌شده (کیلوگرم)',
        'aac-brand-name-label': 'اسم تجاری محصول',
        'aac_brand_name_placeholder': 'اسم تجاری محصول',
        'aac-direction-label': 'نوع',
        'select-aac-direction-default': 'انتخاب کنید',
        'option-aac-right': 'راستگرد',
        'option-aac-left': 'چپگرد',
        'note-label-aac': 'یادداشت',
        'note_placeholder_aac': 'یادداشت‌های اضافی',
        'submit-aac': 'تایید و نمایش خلاصه',
        'aaac-heading': 'جزئیات هادی AAAC',
        'aaac-packaging-label': 'بسته بندی',
        'select-aaac-packaging-default': 'انتخاب کنید',
        'option-aaac-metal-reel': 'قرقره فلزی',
        'option-aaac-wood-reel': 'روی قرقره چوبی',
        'aaac-cross-section-label': 'سطح مقطع نامی (میلی‌متر مربع)',
        'select-aaac-cross-section-default': 'انتخاب کنید',
        'order-by-label-aaac': 'سفارش بر اساس',
        'aaac-order-by-weight-text': 'وزن (کیلوگرم)',
        'aaac-order-by-tiraj-text': 'متراژ (متر)',
        'aaac-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'aaac_weight_placeholder': 'وزن درخواستی',
        'aaac-calculated-tiraj-label': 'متراژ محاسبه‌شده (متر)',
        'aaac-tiraj-input-label': 'متراژ درخواستی (متر)',
        'aaac-calculated-weight-label': 'وزن محاسبه‌شده (کیلوگرم)',
        'aaac-brand-name-label': 'اسم تجاری محصول',
        'aaac_brand_name_placeholder': 'اسم تجاری محصول',
        'aaac-direction-label': 'نوع',
        'select-aaac-direction-default': 'انتخاب کنید',
        'option-aaac-right': 'راستگرد',
        'option-aaac-left': 'چپگرد',
        'note-label-aaac': 'یادداشت',
        'note_placeholder_aaac': 'یادداشت‌های اضافی',
        'submit-aaac': 'تایید و نمایش خلاصه',
        'acsr-heading': 'جزئیات هادی ACSR',
        'acsr-packaging-label': 'بسته بندی',
        'select-acsr-packaging-default': 'انتخاب کنید',
        'option-acsr-metal-reel': 'قرقره فلزی',
        'option-acsr-wood-reel': 'روی قرقره چوبی',
        'acsr-cross-section-label': 'سطح مقطع نامی (میلی‌متر مربع)',
        'select-acsr-cross-section-default': 'انتخاب کنید',
        'order-by-label-acsr': 'سفارش بر اساس',
        'acsr-order-by-weight-text': 'وزن (کیلوگرم)',
        'acsr-order-by-tiraj-text': 'متراژ (متر)',
        'acsr-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'acsr_weight_placeholder': 'وزن درخواستی',
        'acsr-calculated-tiraj-label': 'متراژ محاسبه‌شده (متر)',
        'acsr-tiraj-input-label': 'متراژ درخواستی (متر)',
        'acsr-calculated-weight-label': 'وزن محاسبه‌شده (کیلوگرم)',
        'acsr-brand-name-label': 'اسم تجاری محصول',
        'acsr_brand_name_placeholder': 'اسم تجاری محصول',
        'acsr-direction-label': 'نوع',
        'select-acsr-direction-default': 'انتخاب کنید',
        'option-acsr-right': 'راستگرد',
        'option-acsr-left': 'چپگرد',
        'note-label-acsr': 'یادداشت',
        'note_placeholder_acsr': 'یادداشت‌های اضافی',
        'submit-acsr': 'تایید و نمایش خلاصه',
        'abc-heading': 'جزئیات هادی ABC',
        'abc-packaging-label': 'بسته بندی',
        'select-abc-packaging-default': 'انتخاب کنید',
        'option-abc-metal-reel': 'قرقره فلزی',
        'option-abc-wood-reel': 'روی قرقره چوبی',
        'abc-cross-section-label': 'سطح مقطع نامی (میلی‌متر مربع)',
        'select-abc-cross-section-default': 'انتخاب کنید',
        'order-by-label-abc': 'سفارش بر اساس',
        'abc-order-by-weight-text': 'وزن (کیلوگرم)',
        'abc-order-by-tiraj-text': 'متراژ (متر)',
        'abc-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'abc_weight_placeholder': 'وزن درخواستی',
        'abc-calculated-tiraj-label': 'متراژ محاسبه‌شده (متر)',
        'abc-tiraj-input-label': 'متراژ درخواستی (متر)',
        'abc_tiraj_placeholder': 'متراژ درخواستی',
        'abc-calculated-weight-no-cover-label': 'وزن بدون روکش (کیلوگرم)',
        'abc-calculated-weight-with-cover-label': 'وزن با روکش (کیلوگرم)',
        'abc-calculated-total-weight-label': 'وزن کل (کیلوگرم)',
        'abc-brand-name-label': 'اسم تجاری محصول',
        'abc_brand_name_placeholder': 'اسم تجاری محصول',
        'abc-direction-label': 'نوع',
        'select-abc-direction-default': 'انتخاب کنید',
        'option-abc-right': 'راستگرد',
        'option-abc-left': 'چپگرد',
        'note-label-abc': 'یادداشت',
        'note_placeholder_abc': 'یادداشت‌های اضافی',
        'submit-abc': 'تایید و نمایش خلاصه',
        'rod-heading': 'جزئیات Rod',
        'rod-alloy-type-label': 'نوع آلیاژ',
        'select-rod-alloy-default': 'انتخاب کنید',
        'option-rod-pure': 'خالص',
        'option-rod-alloyed': 'آلیاژی',
        'rod-annealing-label': 'آنیل',
        'select-rod-annealing-default': 'انتخاب کنید',
        'option-rod-annealing-yes': 'بشود',
        'option-rod-annealing-no': 'نشود',
        'rod-aging-label': 'ایجینگ',
        'select-rod-aging-default': 'انتخاب کنید',
        'option-rod-aging-yes': 'بشود',
        'option-rod-aging-no': 'نشود',
        'rod-packaging-label': 'بسته بندی',
        'select-rod-packaging-default': 'انتخاب کنید',
        'option-bundle': 'کلاف',
        'option-coil-rod': 'کویل',
        'rod-diameter-label': 'قطر (میلی‌متر مربع)',
        'select-rod-diameter-default': 'انتخاب کنید',
        'rod-temper-label': 'تمپر',
        'select-rod-temper-default': 'انتخاب کنید',
        'rod-order-by-weight-text': 'وزن (کیلوگرم)',
        'rod-order-by-length-text': 'متراژ (متر)',
        'rod-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'rod_weight_placeholder': 'وزن درخواستی',
        'rod-length-input-label': 'متراژ درخواستی (متر)',
        'rod_length_placeholder': 'متراژ درخواستی',
        'note-label-rod': 'یادداشت',
        'note_placeholder_rod': 'یادداشت‌های اضافی',
        'submit-rod': 'تایید و نمایش خلاصه',
        'Aluminium-tray-heading': 'جزئیات ظروف آلومینیوم',
        'tray-capacity-label': 'حجم',
        'select-tray-capacity-default': 'انتخاب کنید',
        'tray-dimensions-label': 'ابعاد',
        'select-tray-dimensions-default': 'ابتدا حجم را انتخاب کنید',
        'tray-quantity-label': 'تعداد',
        'tray_quantity_placeholder': 'تعداد درخواستی',
        'note-label-tray': 'یادداشت',
        'note_placeholder_tray': 'یادداشت‌های اضافی',
        'submit-tray': 'تایید و نمایش خلاصه',
        // SweetAlert & Toastify
        'swal-confirm-title': 'آیا از ثبت سفارش اطمینان دارید؟',
        'swal-confirm-text': 'پس از ثبت امکان ویرایش وجود ندارد!',
        'swal-confirm-btn': 'بله، ثبت کن',
        'swal-cancel-btn': 'لغو',
        'swal-error-title': 'خطا!',
        'swal-error-text': 'در ثبت سفارش مشکلی رخ داده است. لطفاً مجدداً تلاش کنید.',
        'swal-error-btn': 'باشه',
        'toast-success': 'سفارش با موفقیت ثبت شد',
        'toast-error-product-selection': 'لطفاً یک نوع محصول را انتخاب کنید تا به مرحله بعد بروید.',
        'toast-error-required-fields': 'لطفاً فیلدهای الزامی (نام شرکت و شماره تماس) را پر کنید.',
        // Date Picker
        'date-picker-cancel': 'انصراف',
        'date-picker-confirm': 'تایید',
        // SEO
        'seo-description': 'فرم ثبت سفارش آنلاین محصولات آلومینیوم خالص و آلیاژی از شرکت الکامهر کیمیا.',
        'seo-keywords': 'ثبت سفارش، فرم آنلاین، الکامهر کیمیا، آلومینیوم، شمش، گرانول، مفتول، هادی AAC, هادی AAAC, هادی ACSR, هادی ABC, راد، ظروف آلومینیوم',
    },
    'en': {
        'header-title': 'Elka Mehr Kimiya Order Registration',
        'header-subtitle': 'Producer of Pure and Alloyed Aluminium',
        'choose-language-text': 'Choose your language',
        'order-info-heading': 'Order Information',
        'order-type-label': 'Order Type',
        'option-internal': 'Internal Order',
        'option-customer': 'Customer Order',
        'company-person-name-label': 'Company / Person Name',
        'company_person_name_placeholder': 'Enter company or person name',
        'contact-number-label': 'Contact Number',
        'contact_number_placeholder': 'Enter contact number',
        'delivery-date-label': 'Desired Delivery Date',
        'delivery_date_placeholder': 'Select Date',
        'description-label': 'Description',
        'description_placeholder': 'Order description',
        'note-label': 'Please enter your address or email for contact',
        'note_placeholder': 'Please enter your address or email for contact',
        'next-step-1': 'Next Step',
        'product-type-heading': 'Product Type',
        'product-alloy-ingot': 'Alloy Ingot',
        'product-granule': 'Granule',
        'product-wire': 'Wire',
        'product-aac-conductor': 'AAC Conductor',
        'product-aaac-conductor': 'AAAC Conductor',
        'product-abc-conductor': 'ABC Conductor',
        'product-acsr-conductor': 'ACSR Conductor',
        'product-rod': 'Rod',
        'product-Aluminium-tray': 'Aluminium Trays',
        'prev-step-2': 'Previous Step',
        'next-step-2': 'Next Step',
        'nav-back': 'Back',
        'summary-heading': 'Summary and Order Confirmation',
        'summary-title': 'Your Order Summary',
        'summary-order-info': 'Order Information',
        'summary-product-details': 'Product Details',
        'summary-order-type': 'Order Type:',
        'summary-company-person': 'Company / Person Name:',
        'summary-contact-number': 'Contact Number:',
        'summary-delivery-date': 'Delivery Date:',
        'summary-description': 'Description:',
        'summary-note': 'Note:',
        'summary-product-type': 'Product Type:',
        'summary-submit': 'Finalize Order',
        // Product Specific Details
        'alloy-ingot-heading': 'Alloy Ingot Details',
        'alloy-type-label': 'Alloy Type',
        'select-option-default-alloy': 'Select',
        'option-pure': 'Pure',
        'option-alloyed': 'Alloyed',
        'packaging-label-alloy': 'Packaging',
        'select-packaging-default-alloy': 'Select',
        'option-bulk-alloy': 'Bulk',
        'option-pallet-alloy': '1000 kg Pallet',
        'weight-label-alloy': 'Requested Weight (kg)',
        'weight_placeholder': 'Requested weight',
        'standard-label': 'Standard',
        'standard_placeholder': 'Standard',
        'chemical-analysis-label': 'Key Chemical Analysis',
        'chemical_analysis_placeholder': 'Key chemical analysis',
        'note-label-alloy': 'Note',
        'note_placeholder_alloy': 'Additional notes',
        'submit-alloy': 'Confirm and Show Summary',
        'granule-heading': 'Granule Details',
        'granule-alloy-type-label': 'Alloy Type',
        'select-granule-alloy-default': 'Select',
        'option-granule-pure': 'Pure',
        'option-granule-alloyed': 'Alloyed',
        'granule-packaging-label': 'Packaging',
        'select-granule-packaging-default': 'Select',
        'option-jumbo': 'Jumbo',
        'option-bulk-granule': 'Bulk',
        'granule-weight-label': 'Requested Weight (kg)',
        'granule_weight_placeholder': 'Requested weight',
        'granule-note-label': 'Note',
        'granule_note_placeholder': 'Additional notes',
        'submit-granule': 'Confirm and Show Summary',
        'wire-heading': 'Wire Details',
        'wire-alloy-type-label': 'Alloy Type',
        'select-wire-alloy-default': 'Select',
        'option-wire-pure': 'Pure',
        'option-wire-alloyed': 'Alloyed',
        'anneal-label': 'Annealing',
        'select-anneal-default': 'Select',
        'option-anneal-yes': 'Yes',
        'option-anneal-no': 'No',
        'aging-label': 'Aging',
        'select-aging-default': 'Select',
        'option-aging-yes': 'Yes',
        'option-aging-no': 'No',
        'wire-packaging-label': 'Packaging',
        'select-wire-packaging-default': 'Select',
        'option-reel-630': 'Reel 630',
        'option-plastic-reel': 'Plastic Reel',
        'option-wood-reel': 'Wooden Reel',
        'option-coil': 'Coil',
        'wire-cross-section-label': 'Diameter (mm)',
        'wire_cross_section_placeholder': 'Diameter (mm)',
        'order-by-label-wire': 'Order By',
        'wire-order-by-weight-text': 'Weight (kg)',
        'wire-order-by-tiraj-text': 'Length (m)',
        'wire-weight-input-label': 'Requested Weight (kg)',
        'wire_weight_placeholder': 'Requested weight',
        'wire-calculated-tiraj-label': 'Calculated Length (m)',
        'wire-tiraj-input-label': 'Requested Length (m)',
        'wire-calculated-weight-label': 'Calculated Weight (kg)',
        'note-label-wire': 'Note',
        'note_placeholder_wire': 'Additional notes',
        'submit-wire': 'Confirm and Show Summary',
        'aac-heading': 'AAC Conductor Details',
        'aac-packaging-label': 'Packaging',
        'select-aac-packaging-default': 'Select',
        'option-aac-metal-reel': 'Metal Reel',
        'option-aac-wood-reel': 'Wooden Reel',
        'aac-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-aac-cross-section-default': 'Select',
        'order-by-label-aac': 'Order By',
        'aac-order-by-weight-text': 'Weight (kg)',
        'aac-order-by-tiraj-text': 'Length (m)',
        'aac-weight-input-label': 'Requested Weight (kg)',
        'aac_weight_placeholder': 'Requested weight',
        'aac-calculated-tiraj-label': 'Calculated Length (m)',
        'aac-tiraj-input-label': 'Requested Length (m)',
        'aac-calculated-weight-label': 'Calculated Weight (kg)',
        'aac-brand-name-label': 'Product Brand Name',
        'aac_brand_name_placeholder': 'Product brand name',
        'aac-direction-label': 'Type',
        'select-aac-direction-default': 'Select',
        'option-aac-right': 'Right-hand lay',
        'option-aac-left': 'Left-hand lay',
        'note-label-aac': 'Note',
        'note_placeholder_aac': 'Additional notes',
        'submit-aac': 'Confirm and Show Summary',
        'aaac-heading': 'AAAC Conductor Details',
        'aaac-packaging-label': 'Packaging',
        'select-aaac-packaging-default': 'Select',
        'option-aaac-metal-reel': 'Metal Reel',
        'option-aaac-wood-reel': 'Wooden Reel',
        'aaac-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-aaac-cross-section-default': 'Select',
        'order-by-label-aaac': 'Order By',
        'aaac-order-by-weight-text': 'Weight (kg)',
        'aaac-order-by-tiraj-text': 'Length (m)',
        'aaac-weight-input-label': 'Requested Weight (kg)',
        'aaac_weight_placeholder': 'Requested weight',
        'aaac-calculated-tiraj-label': 'Calculated Length (m)',
        'aaac-tiraj-input-label': 'Requested Length (m)',
        'aaac-calculated-weight-label': 'Calculated Weight (kg)',
        'aaac-brand-name-label': 'Product Brand Name',
        'aaac_brand_name_placeholder': 'Product brand name',
        'aaac-direction-label': 'Type',
        'select-aaac-direction-default': 'Select',
        'option-aaac-right': 'Right-hand lay',
        'option-aaac-left': 'Left-hand lay',
        'note-label-aaac': 'Note',
        'note_placeholder_aaac': 'Additional notes',
        'submit-aaac': 'Confirm and Show Summary',
        'acsr-heading': 'ACSR Conductor Details',
        'acsr-packaging-label': 'Packaging',
        'select-acsr-packaging-default': 'Select',
        'option-acsr-metal-reel': 'Metal Reel',
        'option-acsr-wood-reel': 'Wooden Reel',
        'acsr-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-acsr-cross-section-default': 'Select',
        'order-by-label-acsr': 'Order By',
        'acsr-order-by-weight-text': 'Weight (kg)',
        'acsr-order-by-tiraj-text': 'Length (m)',
        'acsr-weight-input-label': 'Requested Weight (kg)',
        'acsr_weight_placeholder': 'Requested weight',
        'acsr-calculated-tiraj-label': 'Calculated Length (m)',
        'acsr-tiraj-input-label': 'Requested Length (m)',
        'acsr-calculated-weight-label': 'Calculated Weight (kg)',
        'acsr-brand-name-label': 'Product Brand Name',
        'acsr_brand_name_placeholder': 'Product brand name',
        'acsr-direction-label': 'Type',
        'select-acsr-direction-default': 'Select',
        'option-acsr-right': 'Right-hand lay',
        'option-acsr-left': 'Left-hand lay',
        'note-label-acsr': 'Note',
        'note_placeholder_acsr': 'Additional notes',
        'submit-acsr': 'Confirm and Show Summary',
        'abc-heading': 'ABC Conductor Details',
        'abc-packaging-label': 'Packaging',
        'select-abc-packaging-default': 'Select',
        'option-abc-metal-reel': 'Metal Reel',
        'option-abc-wood-reel': 'Wooden Reel',
        'abc-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-abc-cross-section-default': 'Select',
        'order-by-label-abc': 'Order By',
        'abc-order-by-weight-text': 'Weight (kg)',
        'abc-order-by-tiraj-text': 'Length (m)',
        'abc-weight-input-label': 'Requested Weight (kg)',
        'abc_weight_placeholder': 'Requested weight',
        'abc-calculated-tiraj-label': 'Calculated Length (m)',
        'abc-tiraj-input-label': 'Requested Length (m)',
        'abc_tiraj_placeholder': 'Requested length',
        'abc-calculated-weight-no-cover-label': 'Weight without Cover (kg)',
        'abc-calculated-weight-with-cover-label': 'Weight with Cover (kg)',
        'abc-calculated-total-weight-label': 'Total Weight (kg)',
        'abc-brand-name-label': 'Product Brand Name',
        'abc_brand_name_placeholder': 'Product brand name',
        'abc-direction-label': 'Type',
        'select-abc-direction-default': 'Select',
        'option-abc-right': 'Right-hand lay',
        'option-abc-left': 'Left-hand lay',
        'note-label-abc': 'Note',
        'note_placeholder_abc': 'Additional notes',
        'submit-abc': 'Confirm and Show Summary',
        'rod-heading': 'Rod Details',
        'rod-alloy-type-label': 'Alloy Type',
        'select-rod-alloy-default': 'Select',
        'option-rod-pure': 'Pure',
        'option-rod-alloyed': 'Alloyed',
        'rod-annealing-label': 'Annealing',
        'select-rod-annealing-default': 'Select',
        'option-rod-annealing-yes': 'Yes',
        'option-rod-annealing-no': 'No',
        'rod-aging-label': 'Aging',
        'select-rod-aging-default': 'Select',
        'option-rod-aging-yes': 'Yes',
        'option-rod-aging-no': 'No',
        'rod-packaging-label': 'Packaging',
        'select-rod-packaging-default': 'Select',
        'option-bundle': 'Bundle',
        'option-coil-rod': 'Coil',
        'rod-diameter-label': 'Diameter (mm²)',
        'select-rod-diameter-default': 'Select',
        'rod-temper-label': 'Temper',
        'select-rod-temper-default': 'Select',
        'rod-order-by-weight-text': 'Weight (kg)',
        'rod-order-by-length-text': 'Length (m)',
        'rod-weight-input-label': 'Requested Weight (kg)',
        'rod_weight_placeholder': 'Requested weight',
        'rod-length-input-label': 'Requested Length (m)',
        'rod_length_placeholder': 'Requested length',
        'note-label-rod': 'Note',
        'note_placeholder_rod': 'Additional notes',
        'submit-rod': 'Confirm and Show Summary',
        'Aluminium-tray-heading': 'Aluminium Tray Details',
        'tray-capacity-label': 'Capacity',
        'select-tray-capacity-default': 'Select',
        'tray-dimensions-label': 'Dimensions',
        'select-tray-dimensions-default': 'Select capacity first',
        'tray-quantity-label': 'Quantity',
        'tray_quantity_placeholder': 'Requested quantity',
        'note-label-tray': 'Note',
        'note_placeholder_tray': 'Additional notes',
        'submit-tray': 'Confirm and Show Summary',
        // SweetAlert & Toastify
        'swal-confirm-title': 'Are you sure you want to submit the order?',
        'swal-confirm-text': 'Once submitted, it cannot be edited!',
        'swal-confirm-btn': 'Yes, submit',
        'swal-cancel-btn': 'Cancel',
        'swal-error-title': 'Error!',
        'swal-error-text': 'An error occurred while submitting the order. Please try again.',
        'swal-error-btn': 'Ok',
        'toast-success': 'Order submitted successfully',
        'toast-error-product-selection': 'Please select a product type to proceed to the next step.',
        'toast-error-required-fields': 'Please fill in the required fields (Company Name and Contact Number).',
        // Date Picker
        'date-picker-cancel': 'Cancel',
        'date-picker-confirm': 'Confirm',
        // SEO
        'seo-description': 'Online order registration form for pure and alloyed aluminum products from Elka Mehr Kimiya company.',
        'seo-keywords': 'order form, online form, Elka Mehr Kimiya, aluminum, ingot, granule, wire, AAC conductor, AAAC conductor, ACSR conductor, ABC conductor, rod, aluminum trays',
    },
    'tr': {
        'header-title': 'Elka Mehr Kimiya Sipariş Kayıt',
        'header-subtitle': 'Saf ve Alaşımlı Alüminyum Üreticisi',
        'choose-language-text': 'Dilinizi Seçin',
        'order-info-heading': 'Sipariş Bilgileri',
        'order-type-label': 'Sipariş Türü',
        'option-internal': 'Dahili Sipariş',
        'option-customer': 'Müşteri Siparişi',
        'company-person-name-label': 'Şirket / Kişi Adı',
        'company_person_name_placeholder': 'Şirket veya kişi adını girin',
        'contact-number-label': 'İletişim Numarası',
        'contact_number_placeholder': 'İletişim numarasını girin',
        'delivery-date-label': 'İstenen Teslim Tarihi',
        'delivery_date_placeholder': 'Tarih Seçin',
        'description-label': 'Açıklama',
        'description_placeholder': 'Sipariş açıklaması',
        'note-label': 'İletişim için adresinizi veya e-posta adresinizi giriniz',
        'note_placeholder': 'İletişim için adresinizi veya e-posta adresinizi giriniz',
        'next-step-1': 'Sonraki Adım',
        'product-type-heading': 'Ürün Tipi',
        'product-alloy-ingot': 'Alaşımlı Külçe',
        'product-granule': 'Granül',
        'product-wire': 'Tel',
        'product-aac-conductor': 'AAC İletken',
        'product-aaac-conductor': 'AAAC İletken',
        'product-abc-conductor': 'ABC İletken',
        'product-acsr-conductor': 'ACSR İletken',
        'product-rod': 'Çubuk',
        'product-Aluminium-tray': 'Alüminyum Kaplar',
        'prev-step-2': 'Önceki Adım',
        'next-step-2': 'Sonraki Adım',
        'nav-back': 'Geri',
        'summary-heading': 'Özet ve Sipariş Onayı',
        'summary-title': 'Sipariş Özetiniz',
        'summary-order-info': 'Sipariş Bilgileri',
        'summary-product-details': 'Ürün Detayları',
        'summary-order-type': 'Sipariş Türü:',
        'summary-company-person': 'Şirket / Kişi Adı:',
        'summary-contact-number': 'İletişim Numarası:',
        'summary-delivery-date': 'Teslim Tarihi:',
        'summary-description': 'Açıklama:',
        'summary-note': 'Not:',
        'summary-product-type': 'Ürün Tipi:',
        'summary-submit': 'Siparişi Kesinleştir',
        // Product Specific Details
        'alloy-ingot-heading': 'Alaşımlı Külçe Detayları',
        'alloy-type-label': 'Alaşımlı Tip',
        'select-option-default-alloy': 'Seçin',
        'option-pure': 'Saf',
        'option-alloyed': 'Alaşım',
        'packaging-label-alloy': 'Ambalaj',
        'select-packaging-default-alloy': 'Seçin',
        'option-bulk-alloy': 'Dökme',
        'option-pallet-alloy': '1000 kg Palet',
        'weight-label-alloy': 'İstenen Ağırlık (kg)',
        'weight_placeholder': 'İstenen ağırlık',
        'standard-label': 'Standart',
        'standard_placeholder': 'Standart',
        'chemical-analysis-label': 'Ana Kimyasal Analiz',
        'chemical_analysis_placeholder': 'Ana kimyasal analiz',
        'note-label-alloy': 'Not',
        'note_placeholder_alloy': 'Ek notlar',
        'submit-alloy': 'Onayla ve Özeti Göster',
        'granule-heading': 'Granül Detayları',
        'granule-alloy-type-label': 'Alaşımlı Tip',
        'select-granule-alloy-default': 'Seçin',
        'option-granule-pure': 'Saf',
        'option-granule-alloyed': 'Alaşım',
        'granule-packaging-label': 'Ambalaj',
        'select-granule-packaging-default': 'Seçin',
        'option-jumbo': 'Jumbo',
        'option-bulk-granule': 'Dökme',
        'granule-weight-label': 'İstenen Ağırlık (kg)',
        'granule_weight_placeholder': 'İstenen ağırlık',
        'granule-note-label': 'Not',
        'granule_note_placeholder': 'Ek notlar',
        'submit-granule': 'Onayla ve Özeti Göster',
        'wire-heading': 'Tel Detayları',
        'wire-alloy-type-label': 'Alaşımlı Tip',
        'select-wire-alloy-default': 'Seçin',
        'option-wire-pure': 'Saf',
        'option-wire-alloyed': 'Alaşım',
        'anneal-label': 'Tavlama',
        'select-anneal-default': 'Seçin',
        'option-anneal-yes': 'Evet',
        'option-anneal-no': 'Hayır',
        'aging-label': 'Yaşlandırma',
        'select-aging-default': 'Seçin',
        'option-aging-yes': 'Evet',
        'option-aging-no': 'Hayır',
        'wire-packaging-label': 'Ambalaj',
        'select-wire-packaging-default': 'Seçin',
        'option-reel-630': '630 Makara',
        'option-plastic-reel': 'Plastik Makara',
        'option-wood-reel': 'Ahşap Makara',
        'option-coil': 'Bobin',
        'wire-cross-section-label': 'Çap (mm)',
        'wire_cross_section_placeholder': 'Çap (mm)',
        'order-by-label-wire': 'Sipariş Kriteri',
        'wire-order-by-weight-text': 'Ağırlık (kg)',
        'wire-order-by-tiraj-text': 'Uzunluk (m)',
        'wire-weight-input-label': 'İstenen Ağırlık (kg)',
        'wire_weight_placeholder': 'İstenen ağırlık',
        'wire-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'wire-tiraj-input-label': 'İstenen Uzunluk (m)',
        'wire-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'note-label-wire': 'Not',
        'note_placeholder_wire': 'Ek notlar',
        'submit-wire': 'Onayla ve Özeti Göster',
        'aac-heading': 'AAC İletken Detayları',
        'aac-packaging-label': 'Ambalaj',
        'select-aac-packaging-default': 'Seçin',
        'option-aac-metal-reel': 'Metal Makara',
        'option-aac-wood-reel': 'Ahşap Makara',
        'aac-cross-section-label': 'Nominal Kesit (mm²)',
        'select-aac-cross-section-default': 'Seçin',
        'order-by-label-aac': 'Sipariş Kriteri',
        'aac-order-by-weight-text': 'Ağırlık (kg)',
        'aac-order-by-tiraj-text': 'Uzunluk (m)',
        'aac-weight-input-label': 'İstenen Ağırlık (kg)',
        'aac_weight_placeholder': 'İstenen ağırlık',
        'aac-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'aac-tiraj-input-label': 'İstenen Uzunluk (m)',
        'aac-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'aac-brand-name-label': 'Ürün Marka Adı',
        'aac_brand_name_placeholder': 'Ürün marka adı',
        'aac-direction-label': 'Tip',
        'select-aac-direction-default': 'Seçin',
        'option-aac-right': 'Sağ burgu',
        'option-aac-left': 'Sol burgu',
        'note-label-aac': 'Not',
        'note_placeholder_aac': 'Ek notlar',
        'submit-aac': 'Onayla ve Özeti Göster',
        'aaac-heading': 'AAAC İletken Detayları',
        'aaac-packaging-label': 'Ambalaj',
        'select-aaac-packaging-default': 'Seçin',
        'option-aaac-metal-reel': 'Metal Makara',
        'option-aaac-wood-reel': 'Ahşap Makara',
        'aaac-cross-section-label': 'Nominal Kesit (mm²)',
        'select-aaac-cross-section-default': 'Seçin',
        'order-by-label-aaac': 'Sipariş Kriteri',
        'aaac-order-by-weight-text': 'Ağırlık (kg)',
        'aaac-order-by-tiraj-text': 'Uzunluk (m)',
        'aaac-weight-input-label': 'İstenen Ağırlık (kg)',
        'aaac_weight_placeholder': 'İstenen ağırlık',
        'aaac-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'aaac-tiraj-input-label': 'İstenen Uzunluk (m)',
        'aaac-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'aaac-brand-name-label': 'Ürün Marka Adı',
        'aaac_brand_name_placeholder': 'Ürün marka adı',
        'aaac-direction-label': 'Tip',
        'select-aaac-direction-default': 'Seçin',
        'option-aaac-right': 'Sağ burgu',
        'option-aaac-left': 'Sol burgu',
        'note-label-aaac': 'Not',
        'note_placeholder_aaac': 'Ek notlar',
        'submit-aaac': 'Onayla ve Özeti Göster',
        'acsr-heading': 'ACSR İletken Detayları',
        'acsr-packaging-label': 'Ambalaj',
        'select-acsr-packaging-default': 'Seçin',
        'option-acsr-metal-reel': 'Metal Makara',
        'option-acsr-wood-reel': 'Ahşap Makara',
        'acsr-cross-section-label': 'Nominal Kesit (mm²)',
        'select-acsr-cross-section-default': 'Seçin',
        'order-by-label-acsr': 'Sipariş Kriteri',
        'acsr-order-by-weight-text': 'Ağırlık (kg)',
        'acsr-order-by-tiraj-text': 'Uzunluk (m)',
        'acsr-weight-input-label': 'İstenen Ağırlık (kg)',
        'acsr_weight_placeholder': 'İstenen ağırlık',
        'acsr-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'acsr-tiraj-input-label': 'İstenen Uzunluk (m)',
        'acsr-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'acsr-brand-name-label': 'Ürün Marka Adı',
        'acsr_brand_name_placeholder': 'Ürün marka adı',
        'acsr-direction-label': 'Tip',
        'select-acsr-direction-default': 'Seçin',
        'option-acsr-right': 'Sağ burgu',
        'option-acsr-left': 'Sol burgu',
        'note-label-acsr': 'Not',
        'note_placeholder_acsr': 'Ek notlar',
        'submit-acsr': 'Onayla ve Özeti Göster',
        'abc-heading': 'ABC İletken Detayları',
        'abc-packaging-label': 'Ambalaj',
        'select-abc-packaging-default': 'Seçin',
        'option-abc-metal-reel': 'Metal Makara',
        'option-abc-wood-reel': 'Ahşap Makara',
        'abc-cross-section-label': 'Nominal Kesit (mm²)',
        'select-abc-cross-section-default': 'Seçin',
        'order-by-label-abc': 'Sipariş Kriteri',
        'abc-order-by-weight-text': 'Ağırlık (kg)',
        'abc-order-by-tiraj-text': 'Uzunluk (m)',
        'abc-weight-input-label': 'İstenen Ağırlık (kg)',
        'abc_weight_placeholder': 'İstenen ağırlık',
        'abc-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'abc-tiraj-input-label': 'İstenen Uzunluk (m)',
        'abc_tiraj_placeholder': 'İstenen uzunluk',
        'abc-calculated-weight-no-cover-label': 'Kapaksız Ağırlık (kg)',
        'abc-calculated-weight-with-cover-label': 'Kapaklı Ağırlık (kg)',
        'abc-calculated-total-weight-label': 'Toplam Ağırlık (kg)',
        'abc-brand-name-label': 'Ürün Marka Adı',
        'abc_brand_name_placeholder': 'Ürün marka adı',
        'abc-direction-label': 'Tip',
        'select-abc-direction-default': 'Seçin',
        'option-abc-right': 'Sağ burgu',
        'option-abc-left': 'Sol burgu',
        'note-label-abc': 'Not',
        'note_placeholder_abc': 'Ek notlar',
        'submit-abc': 'Onayla ve Özeti Göster',
        'rod-heading': 'Çubuk Detayları',
        'rod-alloy-type-label': 'Alaşımlı Tip',
        'select-rod-alloy-default': 'Seçin',
        'option-rod-pure': 'Saf',
        'option-rod-alloyed': 'Alaşım',
        'rod-annealing-label': 'Tavlama',
        'select-rod-annealing-default': 'Seçin',
        'option-rod-annealing-yes': 'Evet',
        'option-rod-annealing-no': 'Hayır',
        'rod-aging-label': 'Yaşlandırma',
        'select-rod-aging-default': 'Seçin',
        'option-rod-aging-yes': 'Evet',
        'option-rod-aging-no': 'Hayır',
        'rod-packaging-label': 'Ambalaj',
        'select-rod-packaging-default': 'Seçin',
        'option-bundle': 'Demet',
        'option-coil-rod': 'Bobin',
        'rod-diameter-label': 'Çap (mm²)',
        'select-rod-diameter-default': 'Seçin',
        'rod-temper-label': 'Temper',
        'select-rod-temper-default': 'Seçin',
        'rod-order-by-weight-text': 'Ağırlık (kg)',
        'rod-order-by-length-text': 'Uzunluk (m)',
        'rod-weight-input-label': 'İstenen Ağırlık (kg)',
        'rod_weight_placeholder': 'İstenen ağırlık',
        'rod-length-input-label': 'İstenen Uzunluk (m)',
        'rod_length_placeholder': 'İstenen uzunluk',
        'note-label-rod': 'Not',
        'note_placeholder_rod': 'Ek notlar',
        'submit-rod': 'Onayla ve Özeti Göster',
        'Aluminium-tray-heading': 'Alüminyum Kap Detayları',
        'tray-capacity-label': 'Hacim',
        'select-tray-capacity-default': 'Seçin',
        'tray-dimensions-label': 'Boyutlar',
        'select-tray-dimensions-default': 'Önce hacmi seçin',
        'tray-quantity-label': 'Miktar',
        'tray_quantity_placeholder': 'İstenen miktar',
        'note-label-tray': 'Not',
        'note_placeholder_tray': 'Ek notlar',
        'submit-tray': 'Onayla ve Özeti Göster',
        // SweetAlert & Toastify
        'swal-confirm-title': 'Siparişinizi göndermek istediğinizden emin misiniz?',
        'swal-confirm-text': 'Gönderildikten sonra düzenlenemez!',
        'swal-confirm-btn': 'Evet, gönder',
        'swal-cancel-btn': 'İptal',
        'swal-error-title': 'Hata!',
        'swal-error-text': 'Sipariş gönderilirken bir hata oluştu. Lütfen tekrar deneyin.',
        'swal-error-btn': 'Tamam',
        'toast-success': 'Sipariş başarıyla gönderildi',
        'toast-error-product-selection': 'Lütfen bir ürün tipi seçerek bir sonraki adıma geçin.',
        'toast-error-required-fields': 'Lütfen zorunlu alanları (Şirket Adı ve İletişim Numarası) doldurun.',
        // Date Picker
        'date-picker-cancel': 'İptal',
        'date-picker-confirm': 'Onayla',
        // SEO
        'seo-description': 'Online sipariş kayıt formu saf ve alaşımlı alüminyum ürünleri için Elka Mehr Kimiya şirketinden.',
        'seo-keywords': 'sipariş formu, online form, Elka Mehr Kimiya, alüminyum, külçe, granül, tel, AAC iletken, AAAC iletken, ACSR iletken, ABC iletken, çubuk, alüminyum kaplar',
    },
    'ar': {
        'header-title': 'تسجيل طلبات شركة الكامهر كيميا',
        'header-subtitle': 'منتج الألومنيوم النقي والسبائك',
        'choose-language-text': 'اختر لغتك',
        'order-info-heading': 'معلومات الطلب',
        'order-type-label': 'نوع الطلب',
        'option-internal': 'طلب داخلي',
        'option-customer': 'طلب عميل',
        'company-person-name-label': 'اسم الشركة / الشخص',
        'company_person_name_placeholder': 'أدخل اسم الشركة أو الشخص',
        'contact-number-label': 'رقم الاتصال',
        'contact_number_placeholder': 'أدخل رقم الاتصال',
        'delivery-date-label': 'تاريخ التسليم المطلوب',
        'delivery_date_placeholder': 'اختر التاريخ',
        'description-label': 'الوصف',
        'description_placeholder': 'وصف الطلب',
        'note-label': 'يرجى إدخال العنوان أو البريد الإلكتروني للتواصل',
        'note_placeholder': 'يرجى إدخال العنوان أو البريد الإلكتروني للتواصل',
        'next-step-1': 'الخطوة التالية',
        'product-type-heading': 'نوع المنتج',
        'product-alloy-ingot': 'سبائك الألومنيوم',
        'product-granule': 'حبيبات',
        'product-wire': 'أسلاك',
        'product-aac-conductor': 'موصل AAC',
        'product-aaac-conductor': 'موصل AAAC',
        'product-abc-conductor': 'موصل ABC',
        'product-acsr-conductor': 'موصل ACSR',
        'product-rod': 'قضيب',
        'product-Aluminium-tray': 'أوعية ألومنيوم',
        'prev-step-2': 'الخطوة السابقة',
        'next-step-2': 'الخطوة التالية',
        'nav-back': 'العودة',
        'summary-heading': 'ملخص وتأكيد الطلب',
        'summary-title': 'ملخص طلبك',
        'summary-order-info': 'معلومات الطلب',
        'summary-product-details': 'تفاصيل المنتج',
        'summary-order-type': 'نوع الطلب:',
        'summary-company-person': 'اسم الشركة / الشخص:',
        'summary-contact-number': 'رقم الاتصال:',
        'summary-delivery-date': 'تاريخ التسليم:',
        'summary-description': 'الوصف:',
        'summary-note': 'ملاحظة:',
        'summary-product-type': 'نوع المنتج:',
        'summary-submit': 'تأكيد الطلب',
        // Product Specific Details
        'alloy-ingot-heading': 'تفاصيل سبائك الألومنيوم',
        'alloy-type-label': 'نوع السبائك',
        'select-option-default-alloy': 'اختر',
        'option-pure': 'نقي',
        'option-alloyed': 'مخلوط',
        'packaging-label-alloy': 'التعبئة والتغليف',
        'select-packaging-default-alloy': 'اختر',
        'option-bulk-alloy': 'كمية كبيرة',
        'option-pallet-alloy': 'باليت 1000 كجم',
        'weight-label-alloy': 'الوزن المطلوب (كجم)',
        'weight_placeholder': 'الوزن المطلوب',
        'standard-label': 'المعيار',
        'standard_placeholder': 'المعيار',
        'chemical-analysis-label': 'تحليل كيميائي رئيسي',
        'chemical_analysis_placeholder': 'تحليل كيميائي رئيسي',
        'note-label-alloy': 'ملاحظة',
        'note_placeholder_alloy': 'ملاحظات إضافية',
        'submit-alloy': 'تأكيد وعرض الملخص',
        'granule-heading': 'تفاصيل الحبيبات',
        'granule-alloy-type-label': 'نوع السبائك',
        'select-granule-alloy-default': 'اختر',
        'option-granule-pure': 'نقي',
        'option-granule-alloyed': 'مخلوط',
        'granule-packaging-label': 'التعبئة والتغليف',
        'select-granule-packaging-default': 'اختر',
        'option-jumbo': 'جامبو',
        'option-bulk-granule': 'كمية كبيرة',
        'granule-weight-label': 'الوزن المطلوب (كجم)',
        'granule_weight_placeholder': 'الوزن المطلوب',
        'granule-note-label': 'ملاحظة',
        'granule_note_placeholder': 'ملاحظات إضافية',
        'submit-granule': 'تأكيد وعرض الملخص',
        'wire-heading': 'تفاصيل الأسلاك',
        'wire-alloy-type-label': 'نوع السبائك',
        'select-wire-alloy-default': 'اختر',
        'option-wire-pure': 'نقي',
        'option-wire-alloyed': 'مخلوط',
        'anneal-label': 'التليين',
        'select-anneal-default': 'اختر',
        'option-anneal-yes': 'نعم',
        'option-anneal-no': 'لا',
        'aging-label': 'التقادم',
        'select-aging-default': 'اختر',
        'option-aging-yes': 'نعم',
        'option-aging-no': 'لا',
        'wire-packaging-label': 'التعبئة والتغليف',
        'select-wire-packaging-default': 'اختر',
        'option-reel-630': 'بكرة 630',
        'option-plastic-reel': 'بكرة بلاستيكية',
        'option-wood-reel': 'بكرة خشبية',
        'option-coil': 'ملف',
        'wire-cross-section-label': 'القطر (مم)',
        'wire_cross_section_placeholder': 'القطر (مم)',
        'order-by-label-wire': 'الطلب حسب',
        'wire-order-by-weight-text': 'الوزن (كجم)',
        'wire-order-by-tiraj-text': 'الطول (متر)',
        'wire-weight-input-label': 'الوزن المطلوب (كجم)',
        'wire-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'wire-tiraj-input-label': 'الطول المطلوب (متر)',
        'wire-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'note-label-wire': 'ملاحظة',
        'note_placeholder_wire': 'ملاحظات إضافية',
        'submit-wire': 'تأكيد وعرض الملخص',
        'aac-heading': 'تفاصيل موصل AAC',
        'aac-packaging-label': 'التعبئة والتغليف',
        'select-aac-packaging-default': 'اختر',
        'option-aac-metal-reel': 'بكرة معدنية',
        'option-aac-wood-reel': 'بكرة خشبية',
        'aac-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-aac-cross-section-default': 'اختر',
        'order-by-label-aac': 'الطلب حسب',
        'aac-order-by-weight-text': 'الوزن (كجم)',
        'aac-order-by-tiraj-text': 'الطول (متر)',
        'aac-weight-input-label': 'الوزن المطلوب (كجم)',
        'aac_weight_placeholder': 'الوزن المطلوب',
        'aac-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'aac-tiraj-input-label': 'الطول المطلوب (متر)',
        'aac-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'aac-brand-name-label': 'اسم العلامة التجارية للمنتج',
        'aac_brand_name_placeholder': 'اسم العلامة التجارية للمنتج',
        'aac-direction-label': 'النوع',
        'select-aac-direction-default': 'اختر',
        'option-aac-right': 'اتجاه يمين',
        'option-aac-left': 'اتجاه يسار',
        'note-label-aac': 'ملاحظة',
        'note_placeholder_aac': 'ملاحظات إضافية',
        'submit-aac': 'تأكيد وعرض الملخص',
        'aaac-heading': 'تفاصيل موصل AAAC',
        'aaac-packaging-label': 'التعبئة والتغليف',
        'select-aaac-packaging-default': 'اختر',
        'option-aaac-metal-reel': 'بكرة معدنية',
        'option-aaac-wood-reel': 'بكرة خشبية',
        'aaac-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-aaac-cross-section-default': 'اختر',
        'order-by-label-aaac': 'الطلب حسب',
        'aaac-order-by-weight-text': 'الوزن (كجم)',
        'aaac-order-by-tiraj-text': 'الطول (متر)',
        'aaac-weight-input-label': 'الوزن المطلوب (كجم)',
        'aaac_weight_placeholder': 'الوزن المطلوب',
        'aaac-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'aaac-tiraj-input-label': 'الطول المطلوب (متر)',
        'aaac-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'aaac-brand-name-label': 'اسم العلامة التجارية للمنتج',
        'aaac_brand_name_placeholder': 'اسم العلامة التجارية للمنتج',
        'aaac-direction-label': 'النوع',
        'select-aaac-direction-default': 'اختر',
        'option-aaac-right': 'اتجاه يمين',
        'option-aaac-left': 'اتجاه يسار',
        'note-label-aaac': 'ملاحظة',
        'note_placeholder_aaac': 'ملاحظات إضافية',
        'submit-aaac': 'تأكيد وعرض الملخص',
        'acsr-heading': 'تفاصيل موصل ACSR',
        'acsr-packaging-label': 'التعبئة والتغليف',
        'select-acsr-packaging-default': 'اختر',
        'option-acsr-metal-reel': 'بكرة معدنية',
        'option-acsr-wood-reel': 'بكرة خشبية',
        'acsr-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-acsr-cross-section-default': 'اختر',
        'order-by-label-acsr': 'الطلب حسب',
        'acsr-order-by-weight-text': 'الوزن (كجم)',
        'acsr-order-by-tiraj-text': 'الطول (متر)',
        'acsr-weight-input-label': 'الوزن المطلوب (كجم)',
        'acsr_weight_placeholder': 'الوزن المطلوب',
        'acsr-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'acsr-tiraj-input-label': 'الطول المطلوب (متر)',
        'acsr-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'acsr-brand-name-label': 'اسم العلامة التجارية للمنتج',
        'acsr_brand_name_placeholder': 'اسم العلامة التجارية للمنتج',
        'acsr-direction-label': 'النوع',
        'select-acsr-direction-default': 'اختر',
        'option-acsr-right': 'اتجاه يمين',
        'option-acsr-left': 'اتجاه يسار',
        'note-label-acsr': 'ملاحظة',
        'note_placeholder_acsr': 'ملاحظات إضافية',
        'submit-acsr': 'تأكيد وعرض الملخص',
        'abc-heading': 'تفاصيل موصل ABC',
        'abc-packaging-label': 'التعبئة والتغليف',
        'select-abc-packaging-default': 'اختر',
        'option-abc-metal-reel': 'بكرة معدنية',
        'option-abc-wood-reel': 'بكرة خشبية',
        'abc-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-abc-cross-section-default': 'اختر',
        'order-by-label-abc': 'الطلب حسب',
        'abc-order-by-weight-text': 'الوزن (كجم)',
        'abc-order-by-tiraj-text': 'الطول (متر)',
        'abc-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'abc_weight_placeholder': 'وزن درخواستی',
        'abc-calculated-tiraj-label': 'متراژ محاسبه‌شده (متر)',
        'abc-tiraj-input-label': 'متراژ درخواستی (متر)',
        'abc_tiraj_placeholder': 'متراژ درخواستی',
        'abc-calculated-weight-no-cover-label': 'وزن بدون روکش (کیلوگرم)',
        'abc-calculated-weight-with-cover-label': 'وزن با روکش (کیلوگرم)',
        'abc-calculated-total-weight-label': 'وزن کل (کیلوگرم)',
        'abc-brand-name-label': 'اسم تجاری محصول',
        'abc_brand_name_placeholder': 'اسم تجاری محصول',
        'abc-direction-label': 'نوع',
        'select-abc-direction-default': 'اختر',
        'option-abc-right': 'اتجاه يمين',
        'option-abc-left': 'اتجاه يسار',
        'note-label-abc': 'ملاحظة',
        'note_placeholder_abc': 'ملاحظات إضافية',
        'submit-abc': 'تأكيد وعرض الملخص',
        'rod-heading': 'جزئیات Rod',
        'rod-alloy-type-label': 'نوع آلیاژ',
        'select-rod-alloy-default': 'انتخاب کنید',
        'option-rod-pure': 'خالص',
        'option-rod-alloyed': 'آلیاژی',
        'rod-annealing-label': 'آنیل',
        'select-rod-annealing-default': 'انتخاب کنید',
        'option-rod-annealing-yes': 'بشود',
        'option-rod-annealing-no': 'نشود',
        'rod-aging-label': 'ایجینگ',
        'select-rod-aging-default': 'انتخاب کنید',
        'option-rod-aging-yes': 'بشود',
        'option-rod-aging-no': 'نشود',
        'rod-packaging-label': 'بسته بندی',
        'select-rod-packaging-default': 'انتخاب کنید',
        'option-bundle': 'کلاف',
        'option-coil-rod': 'کویل',
        'rod-diameter-label': 'قطر (میلی‌متر مربع)',
        'select-rod-diameter-default': 'انتخاب کنید',
        'rod-temper-label': 'تمپر',
        'select-rod-temper-default': 'انتخاب کنید',
        'rod-order-by-weight-text': 'وزن (کیلوگرم)',
        'rod-order-by-length-text': 'متراژ (متر)',
        'rod-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'rod_weight_placeholder': 'وزن درخواستی',
        'rod-length-input-label': 'متراژ درخواستی (متر)',
        'rod_length_placeholder': 'متراژ درخواستی',
        'note-label-rod': 'یادداشت',
        'note_placeholder_rod': 'یادداشت‌های اضافی',
        'submit-rod': 'تایید و نمایش خلاصه',
        'Aluminium-tray-heading': 'جزئیات ظروف آلومینیوم',
        'tray-capacity-label': 'حجم',
        'select-tray-capacity-default': 'انتخاب کنید',
        'tray-dimensions-label': 'ابعاد',
        'select-tray-dimensions-default': 'ابتدا حجم را انتخاب کنید',
        'tray-quantity-label': 'تعداد',
        'tray_quantity_placeholder': 'تعداد درخواستی',
        'note-label-tray': 'یادداشت',
        'note_placeholder_tray': 'یادداشت‌های اضافی',
        'submit-tray': 'تایید و نمایش خلاصه',
        // SweetAlert & Toastify
        'swal-confirm-title': 'آیا از ثبت سفارش اطمینان دارید؟',
        'swal-confirm-text': 'پس از ثبت امکان ویرایش وجود ندارد!',
        'swal-confirm-btn': 'بله، ثبت کن',
        'swal-cancel-btn': 'لغو',
        'swal-error-title': 'خطا!',
        'swal-error-text': 'در ثبت سفارش مشکلی رخ داده است. لطفاً مجدداً تلاش کنید.',
        'swal-error-btn': 'باشه',
        'toast-success': 'سفارش با موفقیت ثبت شد',
        'toast-error-product-selection': 'لطفاً یک نوع محصول را انتخاب کنید تا به مرحله بعد بروید.',
        'toast-error-required-fields': 'لطفاً فیلدهای الزامی (نام شرکت و شماره تماس) را پر کنید.',
        // Date Picker
        'date-picker-cancel': 'انصراف',
        'date-picker-confirm': 'تایید',
        // SEO
        'seo-description': 'فرم ثبت سفارش آنلاین محصولات آلومینیوم خالص و آلیاژی از شرکت الکامهر کیمیا.',
        'seo-keywords': 'ثبت سفارش، فرم آنلاین، الکامهر کیمیا، آلومینیوم، شمش، گرانول، مفتول، هادی AAC, هادی AAAC, هادی ACSR, هادی ABC, راد، ظروف آلومینیوم',
    },
    'en': {
        'header-title': 'Elka Mehr Kimiya Order Registration',
        'header-subtitle': 'Producer of Pure and Alloyed Aluminium',
        'choose-language-text': 'Choose your language',
        'order-info-heading': 'Order Information',
        'order-type-label': 'Order Type',
        'option-internal': 'Internal Order',
        'option-customer': 'Customer Order',
        'company-person-name-label': 'Company / Person Name',
        'company_person_name_placeholder': 'Enter company or person name',
        'contact-number-label': 'Contact Number',
        'contact_number_placeholder': 'Enter contact number',
        'delivery-date-label': 'Desired Delivery Date',
        'delivery_date_placeholder': 'Select Date',
        'description-label': 'Description',
        'description_placeholder': 'Order description',
        'note-label': 'Note',
        'note_placeholder': 'Additional notes',
        'next-step-1': 'Next Step',
        'product-type-heading': 'Product Type',
        'product-alloy-ingot': 'Alloy Ingot',
        'product-granule': 'Granule',
        'product-wire': 'Wire',
        'product-aac-conductor': 'AAC Conductor',
        'product-aaac-conductor': 'AAAC Conductor',
        'product-abc-conductor': 'ABC Conductor',
        'product-acsr-conductor': 'ACSR Conductor',
        'product-rod': 'Rod',
        'product-Aluminium-tray': 'Aluminium Trays',
        'prev-step-2': 'Previous Step',
        'next-step-2': 'Next Step',
        'nav-back': 'Back',
        'summary-heading': 'Summary and Order Confirmation',
        'summary-title': 'Your Order Summary',
        'summary-order-info': 'Order Information',
        'summary-product-details': 'Product Details',
        'summary-order-type': 'Order Type:',
        'summary-company-person': 'Company / Person Name:',
        'summary-contact-number': 'Contact Number:',
        'summary-delivery-date': 'Delivery Date:',
        'summary-description': 'Description:',
        'summary-note': 'Note:',
        'summary-product-type': 'Product Type:',
        'summary-submit': 'Finalize Order',
        // Product Specific Details
        'alloy-ingot-heading': 'Alloy Ingot Details',
        'alloy-type-label': 'Alloy Type',
        'select-option-default-alloy': 'Select',
        'option-pure': 'Pure',
        'option-alloyed': 'Alloyed',
        'packaging-label-alloy': 'Packaging',
        'select-packaging-default-alloy': 'Select',
        'option-bulk-alloy': 'Bulk',
        'option-pallet-alloy': '1000 kg Pallet',
        'weight-label-alloy': 'Requested Weight (kg)',
        'weight_placeholder': 'Requested weight',
        'standard-label': 'Standard',
        'standard_placeholder': 'Standard',
        'chemical-analysis-label': 'Key Chemical Analysis',
        'chemical_analysis_placeholder': 'Key chemical analysis',
        'note-label-alloy': 'Note',
        'note_placeholder_alloy': 'Additional notes',
        'submit-alloy': 'Confirm and Show Summary',
        'granule-heading': 'Granule Details',
        'granule-alloy-type-label': 'Alloy Type',
        'select-granule-alloy-default': 'Select',
        'option-granule-pure': 'Pure',
        'option-granule-alloyed': 'Alloyed',
        'granule-packaging-label': 'Packaging',
        'select-granule-packaging-default': 'Select',
        'option-jumbo': 'Jumbo',
        'option-bulk-granule': 'Bulk',
        'granule-weight-label': 'Requested Weight (kg)',
        'granule_weight_placeholder': 'Requested weight',
        'granule-note-label': 'Note',
        'granule_note_placeholder': 'Additional notes',
        'submit-granule': 'Confirm and Show Summary',
        'wire-heading': 'Wire Details',
        'wire-alloy-type-label': 'Alloy Type',
        'select-wire-alloy-default': 'Select',
        'option-wire-pure': 'Pure',
        'option-wire-alloyed': 'Alloyed',
        'anneal-label': 'Annealing',
        'select-anneal-default': 'Select',
        'option-anneal-yes': 'Yes',
        'option-anneal-no': 'No',
        'aging-label': 'Aging',
        'select-aging-default': 'Select',
        'option-aging-yes': 'Yes',
        'option-aging-no': 'No',
        'wire-packaging-label': 'Packaging',
        'select-wire-packaging-default': 'Select',
        'option-reel-630': 'Reel 630',
        'option-plastic-reel': 'Plastic Reel',
        'option-wood-reel': 'Wooden Reel',
        'option-coil': 'Coil',
        'wire-cross-section-label': 'Diameter (mm)',
        'wire_cross_section_placeholder': 'Diameter (mm)',
        'order-by-label-wire': 'Order By',
        'wire-order-by-weight-text': 'Weight (kg)',
        'wire-order-by-tiraj-text': 'Length (m)',
        'wire-weight-input-label': 'Requested Weight (kg)',
        'wire_weight_placeholder': 'Requested weight',
        'wire-calculated-tiraj-label': 'Calculated Length (m)',
        'wire-tiraj-input-label': 'Requested Length (m)',
        'wire-calculated-weight-label': 'Calculated Weight (kg)',
        'note-label-wire': 'Note',
        'note_placeholder_wire': 'Additional notes',
        'submit-wire': 'Confirm and Show Summary',
        'aac-heading': 'AAC Conductor Details',
        'aac-packaging-label': 'Packaging',
        'select-aac-packaging-default': 'Select',
        'option-aac-metal-reel': 'Metal Reel',
        'option-aac-wood-reel': 'Wooden Reel',
        'aac-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-aac-cross-section-default': 'Select',
        'order-by-label-aac': 'Order By',
        'aac-order-by-weight-text': 'Weight (kg)',
        'aac-order-by-tiraj-text': 'Length (m)',
        'aac-weight-input-label': 'Requested Weight (kg)',
        'aac_weight_placeholder': 'Requested weight',
        'aac-calculated-tiraj-label': 'Calculated Length (m)',
        'aac-tiraj-input-label': 'Requested Length (m)',
        'aac-calculated-weight-label': 'Calculated Weight (kg)',
        'aac-brand-name-label': 'Product Brand Name',
        'aac_brand_name_placeholder': 'Product brand name',
        'aac-direction-label': 'Type',
        'select-aac-direction-default': 'Select',
        'option-aac-right': 'Right-hand lay',
        'option-aac-left': 'Left-hand lay',
        'note-label-aac': 'Note',
        'note_placeholder_aac': 'Additional notes',
        'submit-aac': 'Confirm and Show Summary',
        'aaac-heading': 'AAAC Conductor Details',
        'aaac-packaging-label': 'Packaging',
        'select-aaac-packaging-default': 'Select',
        'option-aaac-metal-reel': 'Metal Reel',
        'option-aaac-wood-reel': 'Wooden Reel',
        'aaac-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-aaac-cross-section-default': 'Select',
        'order-by-label-aaac': 'Order By',
        'aaac-order-by-weight-text': 'Weight (kg)',
        'aaac-order-by-tiraj-text': 'Length (m)',
        'aaac-weight-input-label': 'Requested Weight (kg)',
        'aaac_weight_placeholder': 'Requested weight',
        'aaac-calculated-tiraj-label': 'Calculated Length (m)',
        'aaac-tiraj-input-label': 'Requested Length (m)',
        'aaac-calculated-weight-label': 'Calculated Weight (kg)',
        'aaac-brand-name-label': 'Product Brand Name',
        'aaac_brand_name_placeholder': 'Product brand name',
        'aaac-direction-label': 'Type',
        'select-aaac-direction-default': 'Select',
        'option-aaac-right': 'Right-hand lay',
        'option-aaac-left': 'Left-hand lay',
        'note-label-aaac': 'Note',
        'note_placeholder_aaac': 'Additional notes',
        'submit-aaac': 'Confirm and Show Summary',
        'acsr-heading': 'ACSR Conductor Details',
        'acsr-packaging-label': 'Packaging',
        'select-acsr-packaging-default': 'Select',
        'option-acsr-metal-reel': 'Metal Reel',
        'option-acsr-wood-reel': 'Wooden Reel',
        'acsr-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-acsr-cross-section-default': 'Select',
        'order-by-label-acsr': 'Order By',
        'acsr-order-by-weight-text': 'Weight (kg)',
        'acsr-order-by-tiraj-text': 'Length (m)',
        'acsr-weight-input-label': 'Requested Weight (kg)',
        'acsr_weight_placeholder': 'Requested weight',
        'acsr-calculated-tiraj-label': 'Calculated Length (m)',
        'acsr-tiraj-input-label': 'Requested Length (m)',
        'acsr-calculated-weight-label': 'Calculated Weight (kg)',
        'acsr-brand-name-label': 'Product Brand Name',
        'acsr_brand_name_placeholder': 'Product brand name',
        'acsr-direction-label': 'Type',
        'select-acsr-direction-default': 'Select',
        'option-acsr-right': 'Right-hand lay',
        'option-acsr-left': 'Left-hand lay',
        'note-label-acsr': 'Note',
        'note_placeholder_acsr': 'Additional notes',
        'submit-acsr': 'Confirm and Show Summary',
        'abc-heading': 'ABC Conductor Details',
        'abc-packaging-label': 'Packaging',
        'select-abc-packaging-default': 'Select',
        'option-abc-metal-reel': 'Metal Reel',
        'option-abc-wood-reel': 'Wooden Reel',
        'abc-cross-section-label': 'Nominal Cross-Section (mm²)',
        'select-abc-cross-section-default': 'Select',
        'order-by-label-abc': 'Order By',
        'abc-order-by-weight-text': 'Weight (kg)',
        'abc-order-by-tiraj-text': 'Length (m)',
        'abc-weight-input-label': 'Requested Weight (kg)',
        'abc_weight_placeholder': 'Requested weight',
        'abc-calculated-tiraj-label': 'Calculated Length (m)',
        'abc-tiraj-input-label': 'Requested Length (m)',
        'abc_tiraj_placeholder': 'Requested length',
        'abc-calculated-weight-no-cover-label': 'Weight without Cover (kg)',
        'abc-calculated-weight-with-cover-label': 'Weight with Cover (kg)',
        'abc-calculated-total-weight-label': 'Total Weight (kg)',
        'abc-brand-name-label': 'Product Brand Name',
        'abc_brand_name_placeholder': 'Product brand name',
        'abc-direction-label': 'Type',
        'select-abc-direction-default': 'Select',
        'option-abc-right': 'Right-hand lay',
        'option-abc-left': 'Left-hand lay',
        'note-label-abc': 'Note',
        'note_placeholder_abc': 'Additional notes',
        'submit-abc': 'Confirm and Show Summary',
        'rod-heading': 'Rod Details',
        'rod-alloy-type-label': 'Alloy Type',
        'select-rod-alloy-default': 'Select',
        'option-rod-pure': 'Pure',
        'option-rod-alloyed': 'Alloyed',
        'rod-annealing-label': 'Annealing',
        'select-rod-annealing-default': 'Select',
        'option-rod-annealing-yes': 'Yes',
        'option-rod-annealing-no': 'No',
        'rod-aging-label': 'Aging',
        'select-rod-aging-default': 'Select',
        'option-rod-aging-yes': 'Yes',
        'option-rod-aging-no': 'No',
        'rod-packaging-label': 'Packaging',
        'select-rod-packaging-default': 'Select',
        'option-bundle': 'Bundle',
        'option-coil-rod': 'Coil',
        'rod-diameter-label': 'Diameter (mm²)',
        'select-rod-diameter-default': 'Select',
        'rod-temper-label': 'Temper',
        'select-rod-temper-default': 'Select',
        'rod-order-by-weight-text': 'Weight (kg)',
        'rod-order-by-length-text': 'Length (m)',
        'rod-weight-input-label': 'Requested Weight (kg)',
        'rod_weight_placeholder': 'Requested weight',
        'rod-length-input-label': 'Requested Length (m)',
        'rod_length_placeholder': 'Requested length',
        'note-label-rod': 'Note',
        'note_placeholder_rod': 'Additional notes',
        'submit-rod': 'Confirm and Show Summary',
        'Aluminium-tray-heading': 'Aluminium Tray Details',
        'tray-capacity-label': 'Capacity',
        'select-tray-capacity-default': 'Select',
        'tray-dimensions-label': 'Dimensions',
        'select-tray-dimensions-default': 'Select capacity first',
        'tray-quantity-label': 'Quantity',
        'tray_quantity_placeholder': 'Requested quantity',
        'note-label-tray': 'Note',
        'note_placeholder_tray': 'Additional notes',
        'submit-tray': 'Confirm and Show Summary',
        // SweetAlert & Toastify
        'swal-confirm-title': 'Are you sure you want to submit the order?',
        'swal-confirm-text': 'Once submitted, it cannot be edited!',
        'swal-confirm-btn': 'Yes, submit',
        'swal-cancel-btn': 'Cancel',
        'swal-error-title': 'Error!',
        'swal-error-text': 'An error occurred while submitting the order. Please try again.',
        'swal-error-btn': 'Ok',
        'toast-success': 'Order submitted successfully',
        'toast-error-product-selection': 'Please select a product type to proceed to the next step.',
        'toast-error-required-fields': 'Please fill in the required fields (Company Name and Contact Number).',
        // Date Picker
        'date-picker-cancel': 'Cancel',
        'date-picker-confirm': 'Confirm',
        // SEO
        'seo-description': 'Online order registration form for pure and alloyed aluminum products from Elka Mehr Kimiya company.',
        'seo-keywords': 'order form, online form, Elka Mehr Kimiya, aluminum, ingot, granule, wire, AAC conductor, AAAC conductor, ACSR conductor, ABC conductor, rod, aluminum trays',
    },
    'tr': {
        'header-title': 'Elka Mehr Kimiya Sipariş Kayıt',
        'header-subtitle': 'Saf ve Alaşımlı Alüminyum Üreticisi',
        'choose-language-text': 'Dilinizi Seçin',
        'order-info-heading': 'Sipariş Bilgileri',
        'order-type-label': 'Sipariş Türü',
        'option-internal': 'Dahili Sipariş',
        'option-customer': 'Müşteri Siparişi',
        'company-person-name-label': 'Şirket / Kişi Adı',
        'company_person_name_placeholder': 'Şirket veya kişi adını girin',
        'contact-number-label': 'İletişim Numarası',
        'contact_number_placeholder': 'İletişim numarasını girin',
        'delivery-date-label': 'İstenen Teslim Tarihi',
        'delivery_date_placeholder': 'Tarih Seçin',
        'description-label': 'Açıklama',
        'description_placeholder': 'Sipariş açıklaması',
        'note-label': 'Not',
        'note_placeholder': 'Ek notlar',
        'next-step-1': 'Sonraki Adım',
        'product-type-heading': 'Ürün Tipi',
        'product-alloy-ingot': 'Alaşımlı Külçe',
        'product-granule': 'Granül',
        'product-wire': 'Tel',
        'product-aac-conductor': 'AAC İletken',
        'product-aaac-conductor': 'AAAC İletken',
        'product-abc-conductor': 'ABC İletken',
        'product-acsr-conductor': 'ACSR İletken',
        'product-rod': 'Çubuk',
        'product-Aluminium-tray': 'Alüminyum Kaplar',
        'prev-step-2': 'Önceki Adım',
        'next-step-2': 'Sonraki Adım',
        'nav-back': 'Geri',
        'summary-heading': 'Özet ve Sipariş Onayı',
        'summary-title': 'Sipariş Özetiniz',
        'summary-order-info': 'Sipariş Bilgileri',
        'summary-product-details': 'Ürün Detayları',
        'summary-order-type': 'Sipariş Türü:',
        'summary-company-person': 'Şirket / Kişi Adı:',
        'summary-contact-number': 'İletişim Numarası:',
        'summary-delivery-date': 'Teslim Tarihi:',
        'summary-description': 'Açıklama:',
        'summary-note': 'Not:',
        'summary-product-type': 'Ürün Tipi:',
        'summary-submit': 'Siparişi Kesinleştir',
        // Product Specific Details
        'alloy-ingot-heading': 'Alaşımlı Külçe Detayları',
        'alloy-type-label': 'Alaşımlı Tip',
        'select-option-default-alloy': 'Seçin',
        'option-pure': 'Saf',
        'option-alloyed': 'Alaşım',
        'packaging-label-alloy': 'Ambalaj',
        'select-packaging-default-alloy': 'Seçin',
        'option-bulk-alloy': 'Dökme',
        'option-pallet-alloy': '1000 kg Palet',
        'weight-label-alloy': 'İstenen Ağırlık (kg)',
        'weight_placeholder': 'İstenen ağırlık',
        'standard-label': 'Standart',
        'standard_placeholder': 'Standart',
        'chemical-analysis-label': 'Ana Kimyasal Analiz',
        'chemical_analysis_placeholder': 'Ana kimyasal analiz',
        'note-label-alloy': 'Not',
        'note_placeholder_alloy': 'Ek notlar',
        'submit-alloy': 'Onayla ve Özeti Göster',
        'granule-heading': 'Granül Detayları',
        'granule-alloy-type-label': 'Alaşımlı Tip',
        'select-granule-alloy-default': 'Seçin',
        'option-granule-pure': 'Saf',
        'option-granule-alloyed': 'Alaşım',
        'granule-packaging-label': 'Ambalaj',
        'select-granule-packaging-default': 'Seçin',
        'option-jumbo': 'Jumbo',
        'option-bulk-granule': 'Dökme',
        'granule-weight-label': 'İstenen Ağırlık (kg)',
        'granule_weight_placeholder': 'İstenen ağırlık',
        'granule-note-label': 'Not',
        'granule_note_placeholder': 'Ek notlar',
        'submit-granule': 'Onayla ve Özeti Göster',
        'wire-heading': 'Tel Detayları',
        'wire-alloy-type-label': 'Alaşımlı Tip',
        'select-wire-alloy-default': 'Seçin',
        'option-wire-pure': 'Saf',
        'option-wire-alloyed': 'Alaşım',
        'anneal-label': 'Tavlama',
        'select-anneal-default': 'Seçin',
        'option-anneal-yes': 'Evet',
        'option-anneal-no': 'Hayır',
        'aging-label': 'Yaşlandırma',
        'select-aging-default': 'Seçin',
        'option-aging-yes': 'Evet',
        'option-aging-no': 'Hayır',
        'wire-packaging-label': 'Ambalaj',
        'select-wire-packaging-default': 'Seçin',
        'option-reel-630': '630 Makara',
        'option-plastic-reel': 'Plastik Makara',
        'option-wood-reel': 'Ahşap Makara',
        'option-coil': 'Bobin',
        'wire-cross-section-label': 'Çap (mm)',
        'wire_cross_section_placeholder': 'Çap (mm)',
        'order-by-label-wire': 'Sipariş Kriteri',
        'wire-order-by-weight-text': 'Ağırlık (kg)',
        'wire-order-by-tiraj-text': 'Uzunluk (m)',
        'wire-weight-input-label': 'İstenen Ağırlık (kg)',
        'wire_weight_placeholder': 'İstenen ağırlık',
        'wire-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'wire-tiraj-input-label': 'İstenen Uzunluk (m)',
        'wire-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'note-label-wire': 'Not',
        'note_placeholder_wire': 'Ek notlar',
        'submit-wire': 'Onayla ve Özeti Göster',
        'aac-heading': 'AAC İletken Detayları',
        'aac-packaging-label': 'Ambalaj',
        'select-aac-packaging-default': 'Seçin',
        'option-aac-metal-reel': 'Metal Makara',
        'option-aac-wood-reel': 'Ahşap Makara',
        'aac-cross-section-label': 'Nominal Kesit (mm²)',
        'select-aac-cross-section-default': 'Seçin',
        'order-by-label-aac': 'Sipariş Kriteri',
        'aac-order-by-weight-text': 'Ağırlık (kg)',
        'aac-order-by-tiraj-text': 'Uzunluk (m)',
        'aac-weight-input-label': 'İstenen Ağırlık (kg)',
        'aac_weight_placeholder': 'İstenen ağırlık',
        'aac-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'aac-tiraj-input-label': 'İstenen Uzunluk (m)',
        'aac-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'aac-brand-name-label': 'Ürün Marka Adı',
        'aac_brand_name_placeholder': 'Ürün marka adı',
        'aac-direction-label': 'Tip',
        'select-aac-direction-default': 'Seçin',
        'option-aac-right': 'Sağ burgu',
        'option-aac-left': 'Sol burgu',
        'note-label-aac': 'Not',
        'note_placeholder_aac': 'Ek notlar',
        'submit-aac': 'Onayla ve Özeti Göster',
        'aaac-heading': 'AAAC İletken Detayları',
        'aaac-packaging-label': 'Ambalaj',
        'select-aaac-packaging-default': 'Seçin',
        'option-aaac-metal-reel': 'Metal Makara',
        'option-aaac-wood-reel': 'Ahşap Makara',
        'aaac-cross-section-label': 'Nominal Kesit (mm²)',
        'select-aaac-cross-section-default': 'Seçin',
        'order-by-label-aaac': 'Sipariş Kriteri',
        'aaac-order-by-weight-text': 'Ağırlık (kg)',
        'aaac-order-by-tiraj-text': 'Uzunluk (m)',
        'aaac-weight-input-label': 'İstenen Ağırlık (kg)',
        'aaac_weight_placeholder': 'İstenen ağırlık',
        'aaac-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'aaac-tiraj-input-label': 'İstenen Uzunluk (m)',
        'aaac-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'aaac-brand-name-label': 'Ürün Marka Adı',
        'aaac_brand_name_placeholder': 'Ürün marka adı',
        'aaac-direction-label': 'Tip',
        'select-aaac-direction-default': 'Seçin',
        'option-aaac-right': 'Sağ burgu',
        'option-aaac-left': 'Sol burgu',
        'note-label-aaac': 'Not',
        'note_placeholder_aaac': 'Ek notlar',
        'submit-aaac': 'Onayla ve Özeti Göster',
        'acsr-heading': 'ACSR İletken Detayları',
        'acsr-packaging-label': 'Ambalaj',
        'select-acsr-packaging-default': 'Seçin',
        'option-acsr-metal-reel': 'Metal Makara',
        'option-acsr-wood-reel': 'Ahşap Makara',
        'acsr-cross-section-label': 'Nominal Kesit (mm²)',
        'select-acsr-cross-section-default': 'Seçin',
        'order-by-label-acsr': 'Sipariş Kriteri',
        'acsr-order-by-weight-text': 'Ağırlık (kg)',
        'acsr-order-by-tiraj-text': 'Uzunluk (m)',
        'acsr-weight-input-label': 'İstenen Ağırlık (kg)',
        'acsr_weight_placeholder': 'İstenen ağırlık',
        'acsr-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'acsr-tiraj-input-label': 'İstenen Uzunluk (m)',
        'acsr-calculated-weight-label': 'Hesaplanan Ağırlık (kg)',
        'acsr-brand-name-label': 'Ürün Marka Adı',
        'acsr_brand_name_placeholder': 'Ürün marka adı',
        'acsr-direction-label': 'Tip',
        'select-acsr-direction-default': 'Seçin',
        'option-acsr-right': 'Sağ burgu',
        'option-acsr-left': 'Sol burgu',
        'note-label-acsr': 'Not',
        'note_placeholder_acsr': 'Ek notlar',
        'submit-acsr': 'Onayla ve Özeti Göster',
        'abc-heading': 'ABC İletken Detayları',
        'abc-packaging-label': 'Ambalaj',
        'select-abc-packaging-default': 'Seçin',
        'option-abc-metal-reel': 'Metal Makara',
        'option-abc-wood-reel': 'Ahşap Makara',
        'abc-cross-section-label': 'Nominal Kesit (mm²)',
        'select-abc-cross-section-default': 'Seçin',
        'order-by-label-abc': 'Sipariş Kriteri',
        'abc-order-by-weight-text': 'Ağırlık (kg)',
        'abc-order-by-tiraj-text': 'Uzunluk (m)',
        'abc-weight-input-label': 'İstenen Ağırlık (kg)',
        'abc_weight_placeholder': 'İstenen ağırlık',
        'abc-calculated-tiraj-label': 'Hesaplanan Uzunluk (m)',
        'abc-tiraj-input-label': 'İstenen Uzunluk (m)',
        'abc_tiraj_placeholder': 'İstenen uzunluk',
        'abc-calculated-weight-no-cover-label': 'Kapaksız Ağırlık (kg)',
        'abc-calculated-weight-with-cover-label': 'Kapaklı Ağırlık (kg)',
        'abc-calculated-total-weight-label': 'Toplam Ağırlık (kg)',
        'abc-brand-name-label': 'Ürün Marka Adı',
        'abc_brand_name_placeholder': 'Ürün marka adı',
        'abc-direction-label': 'Tip',
        'select-abc-direction-default': 'Seçin',
        'option-abc-right': 'Sağ burgu',
        'option-abc-left': 'Sol burgu',
        'note-label-abc': 'Not',
        'note_placeholder_abc': 'Ek notlar',
        'submit-abc': 'Onayla ve Özeti Göster',
        'rod-heading': 'Çubuk Detayları',
        'rod-alloy-type-label': 'Alaşımlı Tip',
        'select-rod-alloy-default': 'Seçin',
        'option-rod-pure': 'Saf',
        'option-rod-alloyed': 'Alaşım',
        'rod-annealing-label': 'Tavlama',
        'select-rod-annealing-default': 'Seçin',
        'option-rod-annealing-yes': 'Evet',
        'option-rod-annealing-no': 'Hayır',
        'rod-aging-label': 'Yaşlandırma',
        'select-rod-aging-default': 'Seçin',
        'option-rod-aging-yes': 'Evet',
        'option-rod-aging-no': 'Hayır',
        'rod-packaging-label': 'Ambalaj',
        'select-rod-packaging-default': 'Seçin',
        'option-bundle': 'Demet',
        'option-coil-rod': 'Bobin',
        'rod-diameter-label': 'Çap (mm²)',
        'select-rod-diameter-default': 'Seçin',
        'rod-temper-label': 'Temper',
        'select-rod-temper-default': 'Seçin',
        'rod-order-by-weight-text': 'Ağırlık (kg)',
        'rod-order-by-length-text': 'Uzunluk (m)',
        'rod-weight-input-label': 'İstenen Ağırlık (kg)',
        'rod_weight_placeholder': 'İstenen ağırlık',
        'rod-length-input-label': 'İstenen Uzunluk (m)',
        'rod_length_placeholder': 'İstenen uzunluk',
        'note-label-rod': 'Not',
        'note_placeholder_rod': 'Ek notlar',
        'submit-rod': 'Onayla ve Özeti Göster',
        'Aluminium-tray-heading': 'Alüminyum Kap Detayları',
        'tray-capacity-label': 'Hacim',
        'select-tray-capacity-default': 'Seçin',
        'tray-dimensions-label': 'Boyutlar',
        'select-tray-dimensions-default': 'Önce hacmi seçin',
        'tray-quantity-label': 'Miktar',
        'tray_quantity_placeholder': 'İstenen miktar',
        'note-label-tray': 'Not',
        'note_placeholder_tray': 'Ek notlar',
        'submit-tray': 'Onayla ve Özeti Göster',
        // SweetAlert & Toastify
        'swal-confirm-title': 'Siparişinizi göndermek istediğinizden emin misiniz?',
        'swal-confirm-text': 'Gönderildikten sonra düzenlenemez!',
        'swal-confirm-btn': 'Evet, gönder',
        'swal-cancel-btn': 'İptal',
        'swal-error-title': 'Hata!',
        'swal-error-text': 'Sipariş gönderilirken bir hata oluştu. Lütfen tekrar deneyin.',
        'swal-error-btn': 'Tamam',
        'toast-success': 'Sipariş başarıyla gönderildi',
        'toast-error-product-selection': 'Lütfen bir ürün tipi seçerek bir sonraki adıma geçin.',
        'toast-error-required-fields': 'Lütfen zorunlu alanları (Şirket Adı ve İletişim Numarası) doldurun.',
        // Date Picker
        'date-picker-cancel': 'İptal',
        'date-picker-confirm': 'Onayla',
        // SEO
        'seo-description': 'Online sipariş kayıt formu saf ve alaşımlı alüminyum ürünleri için Elka Mehr Kimiya şirketinden.',
        'seo-keywords': 'sipariş formu, online form, Elka Mehr Kimiya, alüminyum, külçe, granül, tel, AAC iletken, AAAC iletken, ACSR iletken, ABC iletken, çubuk, alüminyum kaplar',
    },
    'ar': {
        'header-title': 'تسجيل طلبات شركة الكامهر كيميا',
        'header-subtitle': 'منتج الألومنيوم النقي والسبائك',
        'choose-language-text': 'اختر لغتك',
        'order-info-heading': 'معلومات الطلب',
        'order-type-label': 'نوع الطلب',
        'option-internal': 'طلب داخلي',
        'option-customer': 'طلب عميل',
        'company-person-name-label': 'اسم الشركة / الشخص',
        'company_person_name_placeholder': 'أدخل اسم الشركة أو الشخص',
        'contact-number-label': 'رقم الاتصال',
        'contact_number_placeholder': 'أدخل رقم الاتصال',
        'delivery-date-label': 'تاريخ التسليم المطلوب',
        'delivery_date_placeholder': 'اختر التاريخ',
        'description-label': 'الوصف',
        'description_placeholder': 'وصف الطلب',
        'note-label': 'ملاحظة',
        'note_placeholder': 'ملاحظات إضافية',
        'next-step-1': 'الخطوة التالية',
        'product-type-heading': 'نوع المنتج',
        'product-alloy-ingot': 'سبائك الألومنيوم',
        'product-granule': 'حبيبات',
        'product-wire': 'أسلاك',
        'product-aac-conductor': 'موصل AAC',
        'product-aaac-conductor': 'موصل AAAC',
        'product-abc-conductor': 'موصل ABC',
        'product-acsr-conductor': 'موصل ACSR',
        'product-rod': 'قضيب',
        'product-Aluminium-tray': 'أوعية ألومنيوم',
        'prev-step-2': 'الخطوة السابقة',
        'next-step-2': 'الخطوة التالية',
        'nav-back': 'العودة',
        'summary-heading': 'ملخص وتأكيد الطلب',
        'summary-title': 'ملخص طلبك',
        'summary-order-info': 'معلومات الطلب',
        'summary-product-details': 'تفاصيل المنتج',
        'summary-order-type': 'نوع الطلب:',
        'summary-company-person': 'اسم الشركة / الشخص:',
        'summary-contact-number': 'رقم الاتصال:',
        'summary-delivery-date': 'تاريخ التسليم:',
        'summary-description': 'الوصف:',
        'summary-note': 'ملاحظة:',
        'summary-product-type': 'نوع المنتج:',
        'summary-submit': 'تأكيد الطلب',
        // Product Specific Details
        'alloy-ingot-heading': 'تفاصيل سبائك الألومنيوم',
        'alloy-type-label': 'نوع السبائك',
        'select-option-default-alloy': 'اختر',
        'option-pure': 'نقي',
        'option-alloyed': 'مخلوط',
        'packaging-label-alloy': 'التعبئة والتغليف',
        'select-packaging-default-alloy': 'اختر',
        'option-bulk-alloy': 'كمية كبيرة',
        'option-pallet-alloy': 'باليت 1000 كجم',
        'weight-label-alloy': 'الوزن المطلوب (كجم)',
        'weight_placeholder': 'الوزن المطلوب',
        'standard-label': 'المعيار',
        'standard_placeholder': 'المعيار',
        'chemical-analysis-label': 'تحليل كيميائي رئيسي',
        'chemical_analysis_placeholder': 'تحليل كيميائي رئيسي',
        'note-label-alloy': 'ملاحظة',
        'note_placeholder_alloy': 'ملاحظات إضافية',
        'submit-alloy': 'تأكيد وعرض الملخص',
        'granule-heading': 'تفاصيل الحبيبات',
        'granule-alloy-type-label': 'نوع السبائك',
        'select-granule-alloy-default': 'اختر',
        'option-granule-pure': 'نقي',
        'option-granule-alloyed': 'مخلوط',
        'granule-packaging-label': 'التعبئة والتغليف',
        'select-granule-packaging-default': 'اختر',
        'option-jumbo': 'جامبو',
        'option-bulk-granule': 'كمية كبيرة',
        'granule-weight-label': 'الوزن المطلوب (كجم)',
        'granule_weight_placeholder': 'الوزن المطلوب',
        'granule-note-label': 'ملاحظة',
        'granule_note_placeholder': 'ملاحظات إضافية',
        'submit-granule': 'تأكيد وعرض الملخص',
        'wire-heading': 'تفاصيل الأسلاك',
        'wire-alloy-type-label': 'نوع السبائك',
        'select-wire-alloy-default': 'اختر',
        'option-wire-pure': 'نقي',
        'option-wire-alloyed': 'مخلوط',
        'anneal-label': 'التليين',
        'select-anneal-default': 'اختر',
        'option-anneal-yes': 'نعم',
        'option-anneal-no': 'لا',
        'aging-label': 'التقادم',
        'select-aging-default': 'اختر',
        'option-aging-yes': 'نعم',
        'option-aging-no': 'لا',
        'wire-packaging-label': 'التعبئة والتغليف',
        'select-wire-packaging-default': 'اختر',
        'option-reel-630': 'بكرة 630',
        'option-plastic-reel': 'بكرة بلاستيكية',
        'option-wood-reel': 'بكرة خشبية',
        'option-coil': 'ملف',
        'wire-cross-section-label': 'القطر (مم)',
        'wire_cross_section_placeholder': 'القطر (مم)',
        'order-by-label-wire': 'الطلب حسب',
        'wire-order-by-weight-text': 'الوزن (كجم)',
        'wire-order-by-tiraj-text': 'الطول (متر)',
        'wire-weight-input-label': 'الوزن المطلوب (كجم)',
        'wire-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'wire-tiraj-input-label': 'الطول المطلوب (متر)',
        'wire-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'note-label-wire': 'ملاحظة',
        'note_placeholder_wire': 'ملاحظات إضافية',
        'submit-wire': 'تأكيد وعرض الملخص',
        'aac-heading': 'تفاصيل موصل AAC',
        'aac-packaging-label': 'التعبئة والتغليف',
        'select-aac-packaging-default': 'اختر',
        'option-aac-metal-reel': 'بكرة معدنية',
        'option-aac-wood-reel': 'بكرة خشبية',
        'aac-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-aac-cross-section-default': 'اختر',
        'order-by-label-aac': 'الطلب حسب',
        'aac-order-by-weight-text': 'الوزن (كجم)',
        'aac-order-by-tiraj-text': 'الطول (متر)',
        'aac-weight-input-label': 'الوزن المطلوب (كجم)',
        'aac_weight_placeholder': 'الوزن المطلوب',
        'aac-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'aac-tiraj-input-label': 'الطول المطلوب (متر)',
        'aac-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'aac-brand-name-label': 'اسم العلامة التجارية للمنتج',
        'aac_brand_name_placeholder': 'اسم العلامة التجارية للمنتج',
        'aac-direction-label': 'النوع',
        'select-aac-direction-default': 'اختر',
        'option-aac-right': 'اتجاه يمين',
        'option-aac-left': 'اتجاه يسار',
        'note-label-aac': 'ملاحظة',
        'note_placeholder_aac': 'ملاحظات إضافية',
        'submit-aac': 'تأكيد وعرض الملخص',
        'aaac-heading': 'تفاصيل موصل AAAC',
        'aaac-packaging-label': 'التعبئة والتغليف',
        'select-aaac-packaging-default': 'اختر',
        'option-aaac-metal-reel': 'بكرة معدنية',
        'option-aaac-wood-reel': 'بكرة خشبية',
        'aaac-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-aaac-cross-section-default': 'اختر',
        'order-by-label-aaac': 'الطلب حسب',
        'aaac-order-by-weight-text': 'الوزن (كجم)',
        'aaac-order-by-tiraj-text': 'الطول (متر)',
        'aaac-weight-input-label': 'الوزن المطلوب (كجم)',
        'aaac_weight_placeholder': 'الوزن المطلوب',
        'aaac-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'aaac-tiraj-input-label': 'الطول المطلوب (متر)',
        'aaac-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'aaac-brand-name-label': 'اسم العلامة التجارية للمنتج',
        'aaac_brand_name_placeholder': 'اسم العلامة التجارية للمنتج',
        'aaac-direction-label': 'النوع',
        'select-aaac-direction-default': 'اختر',
        'option-aaac-right': 'اتجاه يمين',
        'option-aaac-left': 'اتجاه يسار',
        'note-label-aaac': 'ملاحظة',
        'note_placeholder_aaac': 'ملاحظات إضافية',
        'submit-aaac': 'تأكيد وعرض الملخص',
        'acsr-heading': 'تفاصيل موصل ACSR',
        'acsr-packaging-label': 'التعبئة والتغليف',
        'select-acsr-packaging-default': 'اختر',
        'option-acsr-metal-reel': 'بكرة معدنية',
        'option-acsr-wood-reel': 'بكرة خشبية',
        'acsr-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-acsr-cross-section-default': 'اختر',
        'order-by-label-acsr': 'الطلب حسب',
        'acsr-order-by-weight-text': 'الوزن (كجم)',
        'acsr-order-by-tiraj-text': 'الطول (متر)',
        'acsr-weight-input-label': 'الوزن المطلوب (كجم)',
        'acsr_weight_placeholder': 'الوزن المطلوب',
        'acsr-calculated-tiraj-label': 'الطول المحسوب (متر)',
        'acsr-tiraj-input-label': 'الطول المطلوب (متر)',
        'acsr-calculated-weight-label': 'الوزن المحسوب (كجم)',
        'acsr-brand-name-label': 'اسم العلامة التجارية للمنتج',
        'acsr_brand_name_placeholder': 'اسم العلامة التجارية للمنتج',
        'acsr-direction-label': 'نوع',
        'select-acsr-direction-default': 'اختر',
        'option-acsr-right': 'اتجاه يمين',
        'option-acsr-left': 'اتجاه يسار',
        'note-label-acsr': 'ملاحظة',
        'note_placeholder_acsr': 'ملاحظات إضافية',
        'submit-acsr': 'تأكيد وعرض الملخص',
        'abc-heading': 'تفاصيل موصل ABC',
        'abc-packaging-label': 'التعبئة والتغليف',
        'select-abc-packaging-default': 'اختر',
        'option-abc-metal-reel': 'بكرة معدنية',
        'option-abc-wood-reel': 'بكرة خشبية',
        'abc-cross-section-label': 'المقطع العرضي الاسمي (مم²)',
        'select-abc-cross-section-default': 'اختر',
        'order-by-label-abc': 'الطلب حسب',
        'abc-order-by-weight-text': 'الوزن (كجم)',
        'abc-order-by-tiraj-text': 'متراژ (متر)',
        'abc-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'abc_weight_placeholder': 'وزن درخواستی',
        'abc-calculated-tiraj-label': 'متراژ محاسبه‌شده (متر)',
        'abc-tiraj-input-label': 'متراژ درخواستی (متر)',
        'abc_tiraj_placeholder': 'متراژ درخواستی',
        'abc-calculated-weight-no-cover-label': 'وزن بدون روکش (کیلوگرم)',
        'abc-calculated-weight-with-cover-label': 'وزن با روکش (کیلوگرم)',
        'abc-calculated-total-weight-label': 'وزن کل (کیلوگرم)',
        'abc-brand-name-label': 'اسم تجاری محصول',
        'abc_brand_name_placeholder': 'اسم تجاری محصول',
        'abc-direction-label': 'نوع',
        'select-abc-direction-default': 'اختر',
        'option-abc-right': 'اتجاه يمين',
        'option-abc-left': 'اتجاه يسار',
        'note-label-abc': 'ملاحظة',
        'note_placeholder_abc': 'ملاحظات إضافية',
        'submit-abc': 'تأكيد وعرض الملخص',
        'rod-heading': 'جزئیات Rod',
        'rod-alloy-type-label': 'نوع آلیاژ',
        'select-rod-alloy-default': 'انتخاب کنید',
        'option-rod-pure': 'خالص',
        'option-rod-alloyed': 'آلیاژی',
        'rod-annealing-label': 'آنیل',
        'select-rod-annealing-default': 'انتخاب کنید',
        'option-rod-annealing-yes': 'بشود',
        'option-rod-annealing-no': 'نشود',
        'rod-aging-label': 'ایجینگ',
        'select-rod-aging-default': 'انتخاب کنید',
        'option-rod-aging-yes': 'بشود',
        'option-rod-aging-no': 'نشود',
        'rod-packaging-label': 'بسته بندی',
        'select-rod-packaging-default': 'انتخاب کنید',
        'option-bundle': 'کلاف',
        'option-coil-rod': 'کویل',
        'rod-diameter-label': 'قطر (میلی‌متر مربع)',
        'select-rod-diameter-default': 'انتخاب کنید',
        'rod-temper-label': 'تمپر',
        'select-rod-temper-default': 'انتخاب کنید',
        'rod-order-by-weight-text': 'وزن (کیلوگرم)',
        'rod-order-by-length-text': 'متراژ (متر)',
        'rod-weight-input-label': 'وزن درخواستی (کیلوگرم)',
        'rod_weight_placeholder': 'وزن درخواستی',
        'rod-length-input-label': 'متراژ درخواستی (متر)',
        'rod_length_placeholder': 'متراژ درخواستی',
        'note-label-rod': 'یادداشت',
        'note_placeholder_rod': 'یادداشت‌های اضافی',
        'submit-rod': 'تایید وعرض الملخص',
        'Aluminium-tray-heading': 'تفاصيل أوعية الألومنيوم',
        'tray-capacity-label': 'السعة',
        'select-tray-capacity-default': 'اختر',
        'tray-dimensions-label': 'الأبعاد',
        'select-tray-dimensions-default': 'اختر السعة أولا',
        'tray-quantity-label': 'الكمية',
        'tray_quantity_placeholder': 'الكمية المطلوبة',
        'note-label-tray': 'ملاحظة',
        'note_placeholder_tray': 'ملاحظات إضافية',
        'submit-tray': 'تأكيد وعرض الملخص',
        // SweetAlert & Toastify
        'swal-confirm-title': 'هل أنت متأكد من إرسال الطلب؟',
        'swal-confirm-text': 'بمجرد الإرسال، لا يمكن تعديله!',
        'swal-confirm-btn': 'نعم، أرسل',
        'swal-cancel-btn': 'إلغاء',
        'swal-error-title': 'خطأ!',
        'swal-error-text': 'حدث خطأ أثناء إرسال الطلب. يرجى المحاولة مرة أخرى.',
        'swal-error-btn': 'موافق',
        'toast-success': 'تم إرسال الطلب بنجاح',
        'toast-error-product-selection': 'الرجاء تحديد نوع المنتج للمتابعة إلى الخطوة التالية.',
        'toast-error-required-fields': 'الرجاء ملء الحقول الإلزامية (اسم الشركة ورقم الاتصال).',
        // Date Picker
        'date-picker-cancel': 'إلغاء',
        'date-picker-confirm': 'تأكيد',
        // SEO
        'seo-description': 'نموذج تسجيل طلبات عبر الإنترنت لمنتجات الألومنيوم النقية والسبائك من شركة الكامهر كيميا.',
        'seo-keywords': 'نموذج طلب، نموذج عبر الإنترنت، الكامهر كيميا، ألومنيوم، سبيكة، حبيبات، أسلاك، موصل AAC، موصل AAAC، موصل ACSR، موصل ABC، قضيب، أوعية ألومنيوم',
    }
};

